import type { FirmTier, ImpactLevel } from "@/generated/prisma/enums";
import type { Sector } from "@/lib/library/sectors";

/**
 * Pre-built IBS library. Drives the LibraryBrowser drawer launched from
 * /ibs: admins browse, filter by tier or category, and one-click "Add to
 * register" so they don't have to author every IBS from scratch.
 *
 * Each entry mirrors the OrganizationIBS shape with sensible defaults.
 * Codes here are slugs — they get re-coded with the org's IBS_NN sequence
 * on add.
 *
 * Sector tags drive the cross-sector filter on the library grid; an
 * entry can be tagged with multiple sectors when it applies to several
 * (e.g. customer-data-platform applies to banking + insurance + retail).
 */

export type LibraryIBS = {
  slug: string;
  /** Suggested code; replaced with IBS_NN on add. */
  code: string;
  name: string;
  outcome: string;
  category: string;
  /** One or more sectors this IBS applies to. */
  sectors?: Sector[];
  tiers: FirmTier[]; // which firm profiles this is typical for
  toleranceMin: number;
  fcaToleranceMin?: number;
  praToleranceMin?: number;
  criticality: ImpactLevel;
  description?: string;
  customerJourneys?: string[];
  productsCovered?: string[];
  technology?: string[];
  thirdParties?: string[];
  information?: string[];
  processes?: string[];
  coversPeople?: boolean;
  coversProperty?: boolean;
  coversTechnology?: boolean;
  coversDataAvailability?: boolean;
  coversDataIntegrity?: boolean;
  coversThirdParty?: boolean;
};

export const IBS_CATEGORIES = [
  // Banking & financial services
  "Payments",
  "Customer access",
  "Cards & ATM",
  "Lending",
  "Onboarding",
  "Trading",
  "Insurance",
  "Support",
  "Branch & cash",
  "Treasury",
  // Cross-sector
  "Energy supply",
  "Water supply",
  "Telecoms service",
  "Healthcare delivery",
  "Government service",
  "Transport service",
  "Retail commerce",
  "Logistics",
  "Education delivery",
  "Manufacturing",
  "Media delivery",
  "Professional services",
] as const;

export type IBSCategory = (typeof IBS_CATEGORIES)[number];

export const IBS_LIBRARY: LibraryIBS[] = [
  // ─── Payments ──────────────────────────────────────────────────────────
  {
    slug: "faster-payments",
    code: "FPS_OUT",
    name: "Domestic payments (Faster Payments / BACS / CHAPS)",
    outcome: "Existing customers can make and receive same-day GBP payments.",
    category: "Payments",
    sectors: ["banking", "payments-fintech"],
    tiers: ["TIER_1", "TIER_2", "TIER_3"],
    toleranceMin: 120,
    fcaToleranceMin: 240,
    praToleranceMin: 360,
    criticality: "CRITICAL",
    coversTechnology: true,
    coversDataAvailability: true,
    coversThirdParty: true,
    technology: ["Core ledger", "Payments switch", "FPS gateway"],
    thirdParties: ["Pay.UK / FPS", "ClearBank"],
    information: ["Payment instructions", "Account balances"],
    processes: ["Payment authorisation", "Fraud screening"],
    customerJourneys: ["Customer sends a one-off payment", "Customer schedules standing order"],
  },
  {
    slug: "international-payments",
    code: "INT_PAY",
    name: "International payments (SWIFT / SEPA)",
    outcome: "Customers can send and receive cross-border payments.",
    category: "Payments",
    sectors: ["banking", "payments-fintech"],
    tiers: ["TIER_1", "TIER_2"],
    toleranceMin: 240,
    fcaToleranceMin: 480,
    criticality: "HIGH",
    coversTechnology: true,
    coversThirdParty: true,
    technology: ["Payments switch", "SWIFT gateway"],
    thirdParties: ["SWIFT", "Correspondent bank"],
  },
  {
    slug: "direct-debits",
    code: "DD",
    name: "Direct debits & standing orders",
    outcome: "Outbound automated payments execute on schedule.",
    category: "Payments",
    sectors: ["banking", "payments-fintech"],
    tiers: ["TIER_1", "TIER_2", "TIER_3"],
    toleranceMin: 1440,
    criticality: "HIGH",
    coversTechnology: true,
    coversThirdParty: true,
  },

  // ─── Customer access ──────────────────────────────────────────────────
  {
    slug: "online-mobile-banking",
    code: "OMB",
    name: "Online and mobile banking",
    outcome: "Customers can authenticate, see balances and move money via app/web.",
    category: "Customer access",
    sectors: ["banking"],
    tiers: ["TIER_1", "TIER_2"],
    toleranceMin: 60,
    fcaToleranceMin: 120,
    criticality: "CRITICAL",
    coversTechnology: true,
    coversDataAvailability: true,
    technology: ["Mobile API", "Web app", "Identity service"],
    information: ["Account balances", "Transaction history"],
    customerJourneys: ["Customer logs in", "Customer checks balance", "Customer sends payment"],
  },
  {
    slug: "customer-authentication",
    code: "AUTH",
    name: "Customer authentication",
    outcome: "Customers can sign in and step up via 2FA across all channels.",
    category: "Customer access",
    sectors: ["banking"],
    tiers: ["TIER_1", "TIER_2", "TIER_3"],
    toleranceMin: 30,
    criticality: "CRITICAL",
    coversTechnology: true,
    coversThirdParty: true,
    technology: ["Identity service", "OTP service"],
    thirdParties: ["Auth0 / Okta", "Twilio"],
  },
  {
    slug: "balance-access",
    code: "BAL",
    name: "Providing access to balances",
    outcome: "Mobile and online channels surface account balances and statements.",
    category: "Customer access",
    sectors: ["banking"],
    tiers: ["TIER_1", "TIER_2"],
    toleranceMin: 60,
    criticality: "CRITICAL",
    coversTechnology: true,
    coversDataAvailability: true,
  },

  // ─── Cards & ATM ──────────────────────────────────────────────────────
  {
    slug: "card-authorisation",
    code: "CARD_AUTH",
    name: "Card transaction authorisation",
    outcome: "Cardholders can make purchases and ATM withdrawals.",
    category: "Cards & ATM",
    sectors: ["banking", "payments-fintech"],
    tiers: ["TIER_1", "TIER_2"],
    toleranceMin: 60,
    fcaToleranceMin: 120,
    criticality: "CRITICAL",
    coversTechnology: true,
    coversThirdParty: true,
    technology: ["Card auth", "Token vault"],
    thirdParties: ["Visa", "Mastercard", "Marqeta", "Worldpay"],
  },
  {
    slug: "atm-network",
    code: "ATM",
    name: "ATM network access",
    outcome: "Customers can withdraw cash from owned and partner ATMs.",
    category: "Cards & ATM",
    sectors: ["banking", "payments-fintech"],
    tiers: ["TIER_1"],
    toleranceMin: 180,
    criticality: "HIGH",
    coversProperty: true,
    coversTechnology: true,
    coversThirdParty: true,
  },

  // ─── Lending ──────────────────────────────────────────────────────────
  {
    slug: "mortgage-issuance",
    code: "MTG",
    name: "Issuing and completing a secured loan (mortgage)",
    outcome: "Mortgage applications are processed through to completion.",
    category: "Lending",
    sectors: ["banking"],
    tiers: ["TIER_1", "TIER_2"],
    toleranceMin: 480,
    criticality: "HIGH",
    coversTechnology: true,
    coversThirdParty: true,
  },
  {
    slug: "unsecured-lending",
    code: "LOAN",
    name: "Unsecured lending originations",
    outcome: "New consumer or small-business loans can be applied for and decisioned.",
    category: "Lending",
    sectors: ["banking"],
    tiers: ["TIER_1", "TIER_2", "TIER_3"],
    toleranceMin: 480,
    criticality: "MEDIUM",
  },

  // ─── Onboarding ───────────────────────────────────────────────────────
  {
    slug: "deposit-account-opening",
    code: "DEP_OPEN",
    name: "Deposit account opening",
    outcome: "New deposit accounts (savings, fixed-term) can be opened and funded.",
    category: "Onboarding",
    sectors: ["banking", "payments-fintech"],
    tiers: ["TIER_1", "TIER_2", "TIER_3"],
    toleranceMin: 240,
    criticality: "HIGH",
    coversThirdParty: true,
    customerJourneys: [
      "Customer applies online",
      "ID&V check passes",
      "Account is created and funded",
    ],
  },
  {
    slug: "kyc-onboarding",
    code: "KYC",
    name: "Customer onboarding (KYC / KYB)",
    outcome: "New customers can complete identity & sanctions checks and be approved.",
    category: "Onboarding",
    sectors: ["banking", "payments-fintech"],
    tiers: ["TIER_1", "TIER_2", "TIER_3"],
    toleranceMin: 480,
    criticality: "MEDIUM",
    coversThirdParty: true,
    thirdParties: ["Onfido", "ComplyAdvantage", "Sumsub"],
    processes: ["Identity verification", "AML screening", "Sanctions screening"],
    information: ["Customer PII", "KYC documentation"],
  },

  // ─── Trading ──────────────────────────────────────────────────────────
  {
    slug: "wholesale-market",
    code: "WMI",
    name: "Wholesale market access",
    outcome: "Trading desks can execute hedges and access wholesale liquidity.",
    category: "Trading",
    sectors: ["banking", "asset-wealth"],
    tiers: ["TIER_1"],
    toleranceMin: 60,
    praToleranceMin: 240,
    criticality: "CRITICAL",
    coversTechnology: true,
    coversThirdParty: true,
  },
  {
    slug: "t1-settlement",
    code: "STL",
    name: "Trade settlement (T+1)",
    outcome: "Same- or next-day trade settlement to CSDs and counterparties.",
    category: "Trading",
    sectors: ["banking", "asset-wealth"],
    tiers: ["TIER_1"],
    toleranceMin: 120,
    praToleranceMin: 240,
    criticality: "CRITICAL",
  },

  // ─── Insurance ────────────────────────────────────────────────────────
  {
    slug: "claims-fnol",
    code: "FNOL",
    name: "Claims first-notification-of-loss",
    outcome: "Customers can report a claim and get an acknowledgement.",
    category: "Insurance",
    sectors: ["insurance"],
    tiers: ["TIER_3"],
    toleranceMin: 240,
    criticality: "CRITICAL",
    coversPeople: true,
    coversTechnology: true,
  },
  {
    slug: "claims-payment",
    code: "CLM_PAY",
    name: "Claims payment",
    outcome: "Claims can be settled and paid to the customer's account.",
    category: "Insurance",
    sectors: ["insurance"],
    tiers: ["TIER_3"],
    toleranceMin: 1440,
    criticality: "HIGH",
    coversThirdParty: true,
  },
  {
    slug: "policy-quote-bind",
    code: "QUOTE",
    name: "Quote and bind",
    outcome: "New customers can be quoted and bound to a policy.",
    category: "Insurance",
    sectors: ["insurance"],
    tiers: ["TIER_3"],
    toleranceMin: 720,
    criticality: "MEDIUM",
  },
  {
    slug: "policy-renewal",
    code: "RENEW",
    name: "Policy renewal",
    outcome: "Renewal notices issued on time, customers can act on them.",
    category: "Insurance",
    sectors: ["insurance"],
    tiers: ["TIER_3"],
    toleranceMin: 4320,
    criticality: "MEDIUM",
  },

  // ─── Support ──────────────────────────────────────────────────────────
  {
    slug: "customer-support",
    code: "SUP",
    name: "Customer support contact centre",
    outcome: "Inbound customer support across voice, chat and in-app.",
    category: "Support",
    sectors: ["banking", "insurance"],
    tiers: ["TIER_1", "TIER_2", "TIER_3"],
    toleranceMin: 240,
    criticality: "HIGH",
    coversPeople: true,
  },
  {
    slug: "urgent-customer-comms",
    code: "URG_COMMS",
    name: "Urgent customer communications channel",
    outcome: "Authoritative outbound channel for urgent customer notifications.",
    category: "Support",
    sectors: ["banking", "insurance"],
    tiers: ["TIER_1", "TIER_2", "TIER_3"],
    toleranceMin: 120,
    criticality: "HIGH",
    coversTechnology: true,
    coversThirdParty: true,
  },

  // ─── Branch & cash ────────────────────────────────────────────────────
  {
    slug: "branch-counter",
    code: "BRANCH",
    name: "Branch counter services",
    outcome: "Customers can withdraw cash, deposit cheques and seek help in-branch.",
    category: "Branch & cash",
    sectors: ["banking"],
    tiers: ["TIER_1"],
    toleranceMin: 240,
    criticality: "HIGH",
    coversPeople: true,
    coversProperty: true,
    coversTechnology: true,
  },
  {
    slug: "cash-network",
    code: "CASH_NET",
    name: "Cash supply network",
    outcome: "Cash is replenished at branches and ATMs.",
    category: "Branch & cash",
    sectors: ["banking"],
    tiers: ["TIER_1"],
    toleranceMin: 720,
    criticality: "MEDIUM",
    coversThirdParty: true,
  },

  // ─── Treasury ─────────────────────────────────────────────────────────
  {
    slug: "liquidity-management",
    code: "LIQ",
    name: "Intraday liquidity management",
    outcome: "Treasury monitors and adjusts intraday liquidity positions.",
    category: "Treasury",
    sectors: ["banking", "asset-wealth"],
    tiers: ["TIER_1", "TIER_2"],
    toleranceMin: 60,
    praToleranceMin: 240,
    criticality: "CRITICAL",
  },

  // ─── Energy supply ────────────────────────────────────────────────────
  {
    slug: "electricity-supply",
    code: "ELEC_SUP",
    name: "Electricity supply to domestic and commercial customers",
    outcome: "Customers receive uninterrupted electrical supply at agreed voltage and quality.",
    category: "Energy supply",
    sectors: ["energy-utilities"],
    tiers: ["TIER_1", "TIER_2"],
    toleranceMin: 60,
    criticality: "CRITICAL",
    coversTechnology: true,
    coversProperty: true,
    coversThirdParty: true,
    technology: ["SCADA", "DMS", "Smart-meter network"],
    thirdParties: ["ESO / National Grid", "Distribution network operator"],
    processes: ["Network operations", "Switching", "Restoration"],
  },
  {
    slug: "gas-supply",
    code: "GAS_SUP",
    name: "Gas supply to domestic and commercial customers",
    outcome: "Customers receive uninterrupted gas supply at agreed pressure.",
    category: "Energy supply",
    sectors: ["energy-utilities"],
    tiers: ["TIER_1", "TIER_2"],
    toleranceMin: 60,
    criticality: "CRITICAL",
    coversTechnology: true,
    coversProperty: true,
    coversThirdParty: true,
    technology: ["Gas SCADA", "Pressure regulators"],
    thirdParties: ["National Grid Gas", "GDN"],
  },
  {
    slug: "energy-billing",
    code: "ENG_BILL",
    name: "Energy billing and direct-debit collection",
    outcome: "Customers receive accurate bills and direct-debit collections complete on schedule.",
    category: "Energy supply",
    sectors: ["energy-utilities"],
    tiers: ["TIER_1", "TIER_2", "TIER_3"],
    toleranceMin: 1440,
    criticality: "HIGH",
    coversTechnology: true,
    coversDataIntegrity: true,
    technology: ["Billing system", "Tariff engine", "Direct-debit gateway"],
    information: ["Consumption data", "Tariff rates"],
  },
  {
    slug: "smart-meter-reading",
    code: "SMART_READ",
    name: "Smart-meter consumption-data collection",
    outcome: "Half-hourly meter readings are collected, validated and processed for billing.",
    category: "Energy supply",
    sectors: ["energy-utilities"],
    tiers: ["TIER_1", "TIER_2", "TIER_3"],
    toleranceMin: 1440,
    criticality: "HIGH",
    coversTechnology: true,
    coversDataIntegrity: true,
    coversThirdParty: true,
    technology: ["DCC interface", "Meter-data management"],
    thirdParties: ["DCC", "SECAS"],
  },
  {
    slug: "balancing-mechanism",
    code: "BAL_MECH",
    name: "Wholesale energy trading and balancing-mechanism participation",
    outcome: "Trading desks bid into the wholesale market and balancing mechanism to manage portfolio imbalance.",
    category: "Energy supply",
    sectors: ["energy-utilities"],
    tiers: ["TIER_1", "TIER_2"],
    toleranceMin: 60,
    criticality: "CRITICAL",
    coversTechnology: true,
    coversThirdParty: true,
    technology: ["ETRM", "Trayport / ICE connectivity"],
    thirdParties: ["ESO / Elexon", "Exchanges"],
  },
  {
    slug: "prepayment-meter-vending",
    code: "PPM_VEND",
    name: "Prepayment-meter top-up channels",
    outcome: "Prepayment customers can top up via app, in-store and online — keeping supply on.",
    category: "Energy supply",
    sectors: ["energy-utilities"],
    tiers: ["TIER_1", "TIER_2", "TIER_3"],
    toleranceMin: 120,
    criticality: "CRITICAL",
    coversPeople: true,
    coversTechnology: true,
    coversThirdParty: true,
    description: "Vulnerable-customer cohort depends on this for keeping the heating on.",
  },

  // ─── Water supply ─────────────────────────────────────────────────────
  {
    slug: "water-supply",
    code: "WATER_SUP",
    name: "Potable-water supply to domestic and commercial customers",
    outcome: "Customers receive safe, drinkable water at agreed pressure.",
    category: "Water supply",
    sectors: ["energy-utilities"],
    tiers: ["TIER_1", "TIER_2"],
    toleranceMin: 60,
    criticality: "CRITICAL",
    coversTechnology: true,
    coversProperty: true,
    coversDataIntegrity: true,
    technology: ["Treatment-works SCADA", "Distribution network"],
    information: ["Water-quality samples"],
  },
  {
    slug: "wastewater-treatment",
    code: "WASTE_TR",
    name: "Wastewater collection and treatment",
    outcome: "Wastewater is collected, treated and discharged within environmental consents.",
    category: "Water supply",
    sectors: ["energy-utilities"],
    tiers: ["TIER_1", "TIER_2"],
    toleranceMin: 240,
    criticality: "HIGH",
    coversTechnology: true,
    coversProperty: true,
    coversThirdParty: true,
    technology: ["Treatment SCADA"],
    thirdParties: ["Environment Agency", "Ofwat"],
  },

  // ─── Telecoms ─────────────────────────────────────────────────────────
  {
    slug: "mobile-voice",
    code: "MOB_VOICE",
    name: "Mobile voice service",
    outcome: "Customers can make and receive voice calls, including 999 emergency calls.",
    category: "Telecoms service",
    sectors: ["telecoms"],
    tiers: ["TIER_1", "TIER_2"],
    toleranceMin: 60,
    criticality: "CRITICAL",
    coversTechnology: true,
    coversPeople: true,
    technology: ["Mobile core (HSS/UDM)", "Radio access network"],
  },
  {
    slug: "mobile-data",
    code: "MOB_DATA",
    name: "Mobile data service (4G / 5G)",
    outcome: "Customers can use mobile data for browsing, apps, and messaging.",
    category: "Telecoms service",
    sectors: ["telecoms"],
    tiers: ["TIER_1", "TIER_2"],
    toleranceMin: 120,
    criticality: "HIGH",
    coversTechnology: true,
    technology: ["Mobile core", "Packet gateways"],
  },
  {
    slug: "broadband-connectivity",
    code: "BB_CONN",
    name: "Fixed-line broadband connectivity",
    outcome: "Customers receive fixed-line broadband at agreed speeds.",
    category: "Telecoms service",
    sectors: ["telecoms"],
    tiers: ["TIER_1", "TIER_2"],
    toleranceMin: 240,
    criticality: "HIGH",
    coversTechnology: true,
    coversThirdParty: true,
    thirdParties: ["Openreach"],
  },
  {
    slug: "emergency-999-routing",
    code: "EMG_999",
    name: "Emergency-call (999) routing",
    outcome: "999 calls route correctly to the appropriate emergency-service operator.",
    category: "Telecoms service",
    sectors: ["telecoms"],
    tiers: ["TIER_1", "TIER_2"],
    toleranceMin: 5,
    criticality: "CRITICAL",
    coversPeople: true,
    coversTechnology: true,
    description: "Statutory obligation under Ofcom General Conditions; safety-of-life primacy.",
  },
  {
    slug: "telco-billing",
    code: "TEL_BILL",
    name: "Telco billing and direct-debit collection",
    outcome: "Customers receive accurate bills and direct-debit collections complete on schedule.",
    category: "Telecoms service",
    sectors: ["telecoms"],
    tiers: ["TIER_1", "TIER_2", "TIER_3"],
    toleranceMin: 1440,
    criticality: "HIGH",
    coversTechnology: true,
    coversDataIntegrity: true,
  },
  {
    slug: "sms-otp-delivery",
    code: "SMS_OTP",
    name: "SMS one-time-password delivery",
    outcome: "Banks, retailers and other firms can deliver OTP SMS to customers reliably.",
    category: "Telecoms service",
    sectors: ["telecoms", "banking", "payments-fintech"],
    tiers: ["TIER_1", "TIER_2"],
    toleranceMin: 60,
    criticality: "HIGH",
    coversTechnology: true,
    coversThirdParty: true,
  },

  // ─── Healthcare ───────────────────────────────────────────────────────
  {
    slug: "emergency-care",
    code: "EMR_CARE",
    name: "Emergency department (A&E) operations",
    outcome: "Patients arriving at A&E are triaged and treated within clinical-safety thresholds.",
    category: "Healthcare delivery",
    sectors: ["healthcare"],
    tiers: ["TIER_1", "TIER_2"],
    toleranceMin: 30,
    criticality: "CRITICAL",
    coversPeople: true,
    coversTechnology: true,
    coversProperty: true,
  },
  {
    slug: "elective-surgery",
    code: "ELC_SURG",
    name: "Elective surgical operations",
    outcome: "Scheduled elective surgeries proceed safely on the planned date.",
    category: "Healthcare delivery",
    sectors: ["healthcare"],
    tiers: ["TIER_1", "TIER_2"],
    toleranceMin: 1440,
    criticality: "HIGH",
    coversPeople: true,
    coversTechnology: true,
    coversThirdParty: true,
  },
  {
    slug: "pathology-results",
    code: "PATH_RES",
    name: "Pathology results turnaround",
    outcome: "Samples are processed, results validated and returned within clinical-pathway windows.",
    category: "Healthcare delivery",
    sectors: ["healthcare"],
    tiers: ["TIER_1", "TIER_2"],
    toleranceMin: 240,
    criticality: "HIGH",
    coversTechnology: true,
    coversThirdParty: true,
    coversDataIntegrity: true,
  },
  {
    slug: "epr-clinical-access",
    code: "EPR_CLIN",
    name: "Electronic patient record clinical access",
    outcome: "Clinicians can read and write to the patient record during clinical encounters.",
    category: "Healthcare delivery",
    sectors: ["healthcare"],
    tiers: ["TIER_1", "TIER_2"],
    toleranceMin: 60,
    criticality: "CRITICAL",
    coversTechnology: true,
    coversDataAvailability: true,
    coversDataIntegrity: true,
    coversThirdParty: true,
  },
  {
    slug: "icu-monitoring",
    code: "ICU_MON",
    name: "ICU bedside-monitoring",
    outcome: "ICU patient vitals are monitored continuously and alarms reach nursing staff.",
    category: "Healthcare delivery",
    sectors: ["healthcare"],
    tiers: ["TIER_1", "TIER_2"],
    toleranceMin: 5,
    criticality: "CRITICAL",
    coversPeople: true,
    coversTechnology: true,
  },
  {
    slug: "prescribing-dispensing",
    code: "RX_DISP",
    name: "Electronic prescribing and dispensing",
    outcome: "Clinicians can prescribe electronically and pharmacy can dispense without error.",
    category: "Healthcare delivery",
    sectors: ["healthcare"],
    tiers: ["TIER_1", "TIER_2", "TIER_3"],
    toleranceMin: 120,
    criticality: "HIGH",
    coversTechnology: true,
    coversDataIntegrity: true,
    coversThirdParty: true,
  },
  {
    slug: "appointment-booking-health",
    code: "APPT_BOOK",
    name: "Outpatient appointment booking",
    outcome: "Patients can book, change and cancel outpatient appointments via web, app and phone.",
    category: "Healthcare delivery",
    sectors: ["healthcare"],
    tiers: ["TIER_1", "TIER_2"],
    toleranceMin: 240,
    criticality: "MEDIUM",
    coversTechnology: true,
    coversThirdParty: true,
  },
  {
    slug: "gp-consultation",
    code: "GP_CONS",
    name: "Primary-care GP consultation",
    outcome: "Patients can have GP consultations (in-person, phone, video) within practice availability.",
    category: "Healthcare delivery",
    sectors: ["healthcare"],
    tiers: ["TIER_2", "TIER_3"],
    toleranceMin: 240,
    criticality: "HIGH",
    coversPeople: true,
    coversTechnology: true,
    coversThirdParty: true,
  },

  // ─── Government services ───────────────────────────────────────────────
  {
    slug: "benefits-payment",
    code: "BEN_PAY",
    name: "Benefits payment processing",
    outcome: "Claimants receive Universal Credit, PIP, ESA, JSA payments on the scheduled date.",
    category: "Government service",
    sectors: ["government"],
    tiers: ["TIER_1"],
    toleranceMin: 240,
    criticality: "CRITICAL",
    coversTechnology: true,
    coversDataIntegrity: true,
    coversPeople: true,
    description: "Direct vulnerable-citizen financial-harm exposure; political accountability at Secretary-of-State level.",
  },
  {
    slug: "passport-issuance",
    code: "PASS_ISS",
    name: "Passport issuance and renewal",
    outcome: "Citizens applying for passports receive them within published service standards.",
    category: "Government service",
    sectors: ["government"],
    tiers: ["TIER_1"],
    toleranceMin: 4320,
    criticality: "HIGH",
    coversTechnology: true,
    coversThirdParty: true,
    coversPeople: true,
  },
  {
    slug: "tax-collection-online",
    code: "TAX_FILE",
    name: "Online tax-return filing",
    outcome: "Citizens and businesses can file self-assessment and corporate returns via the online portal.",
    category: "Government service",
    sectors: ["government"],
    tiers: ["TIER_1"],
    toleranceMin: 240,
    criticality: "HIGH",
    coversTechnology: true,
    coversDataAvailability: true,
  },
  {
    slug: "voter-registration",
    code: "VOTE_REG",
    name: "Voter-registration and electoral roll",
    outcome: "Citizens can register to vote; the electoral roll is accurate for polling-station and postal-vote operations.",
    category: "Government service",
    sectors: ["government"],
    tiers: ["TIER_1"],
    toleranceMin: 1440,
    criticality: "CRITICAL",
    coversTechnology: true,
    coversDataIntegrity: true,
  },
  {
    slug: "council-tax-collection",
    code: "CT_COLL",
    name: "Council-tax billing and collection",
    outcome: "Households receive accurate council-tax bills and pay within billing cycle.",
    category: "Government service",
    sectors: ["government"],
    tiers: ["TIER_2", "TIER_3"],
    toleranceMin: 1440,
    criticality: "HIGH",
    coversTechnology: true,
    coversDataIntegrity: true,
  },
  {
    slug: "planning-applications",
    code: "PLAN_APP",
    name: "Planning-application receipt and decision",
    outcome: "Citizens and developers can submit planning applications and receive decisions within statutory windows.",
    category: "Government service",
    sectors: ["government"],
    tiers: ["TIER_2", "TIER_3"],
    toleranceMin: 4320,
    criticality: "MEDIUM",
    coversTechnology: true,
    coversThirdParty: true,
  },
  {
    slug: "border-control-egate",
    code: "BORD_CTL",
    name: "Border-control e-gate / passport verification",
    outcome: "Travellers arriving at UK borders are verified and processed at acceptable throughput.",
    category: "Government service",
    sectors: ["government", "aviation-transport"],
    tiers: ["TIER_1"],
    toleranceMin: 60,
    criticality: "CRITICAL",
    coversTechnology: true,
    coversDataAvailability: true,
    coversThirdParty: true,
  },
  {
    slug: "social-care-case-mgmt",
    code: "SC_CASE",
    name: "Adult social-care case management",
    outcome: "Social workers can access cases, assess needs and arrange care packages.",
    category: "Government service",
    sectors: ["government", "healthcare"],
    tiers: ["TIER_2", "TIER_3"],
    toleranceMin: 240,
    criticality: "HIGH",
    coversPeople: true,
    coversTechnology: true,
    coversDataIntegrity: true,
  },

  // ─── Transport ────────────────────────────────────────────────────────
  {
    slug: "air-traffic-control",
    code: "ATC",
    name: "Air-traffic control flight-plan processing",
    outcome: "Flight plans are processed, controllers have full situational picture, aircraft are sequenced safely.",
    category: "Transport service",
    sectors: ["aviation-transport"],
    tiers: ["TIER_1"],
    toleranceMin: 15,
    criticality: "CRITICAL",
    coversTechnology: true,
    coversPeople: true,
  },
  {
    slug: "airline-reservation",
    code: "AIR_RES",
    name: "Airline reservation and check-in",
    outcome: "Customers can book flights, check in, and board within published windows.",
    category: "Transport service",
    sectors: ["aviation-transport"],
    tiers: ["TIER_1", "TIER_2"],
    toleranceMin: 60,
    criticality: "HIGH",
    coversTechnology: true,
    coversThirdParty: true,
  },
  {
    slug: "rail-signalling",
    code: "RAIL_SIG",
    name: "Rail signalling operations",
    outcome: "Trains move safely through the network with correct signalling and ATP.",
    category: "Transport service",
    sectors: ["aviation-transport"],
    tiers: ["TIER_1"],
    toleranceMin: 15,
    criticality: "CRITICAL",
    coversTechnology: true,
    coversProperty: true,
    coversPeople: true,
  },
  {
    slug: "transit-revenue-collection",
    code: "TRA_REV",
    name: "Transit revenue collection (contactless / Oyster-style)",
    outcome: "Customers tap in and out; correct fares deducted; gates operate.",
    category: "Transport service",
    sectors: ["aviation-transport"],
    tiers: ["TIER_1", "TIER_2"],
    toleranceMin: 120,
    criticality: "HIGH",
    coversTechnology: true,
    coversThirdParty: true,
  },
  {
    slug: "ev-charging-network",
    code: "EV_CHRG",
    name: "EV public-charging network operations",
    outcome: "EV drivers can locate, authenticate at and pay for charging across the network.",
    category: "Transport service",
    sectors: ["aviation-transport", "energy-utilities"],
    tiers: ["TIER_2", "TIER_3"],
    toleranceMin: 120,
    criticality: "HIGH",
    coversTechnology: true,
    coversThirdParty: true,
  },

  // ─── Retail commerce ──────────────────────────────────────────────────
  {
    slug: "online-checkout",
    code: "OL_CHK",
    name: "Online checkout and payment processing",
    outcome: "Customers can place orders and pay successfully on the website / app.",
    category: "Retail commerce",
    sectors: ["retail-ecommerce"],
    tiers: ["TIER_1", "TIER_2"],
    toleranceMin: 60,
    criticality: "CRITICAL",
    coversTechnology: true,
    coversThirdParty: true,
  },
  {
    slug: "epos-instore",
    code: "EPOS",
    name: "Electronic point-of-sale in-store",
    outcome: "Customers can pay at the till; tills are operational across the estate.",
    category: "Retail commerce",
    sectors: ["retail-ecommerce"],
    tiers: ["TIER_1", "TIER_2"],
    toleranceMin: 30,
    criticality: "CRITICAL",
    coversTechnology: true,
    coversProperty: true,
    coversThirdParty: true,
  },
  {
    slug: "order-fulfilment",
    code: "ORD_FUL",
    name: "Order fulfilment and dispatch",
    outcome: "Customer orders are picked, packed and dispatched within the published cut-off.",
    category: "Retail commerce",
    sectors: ["retail-ecommerce", "logistics"],
    tiers: ["TIER_1", "TIER_2"],
    toleranceMin: 720,
    criticality: "HIGH",
    coversProperty: true,
    coversTechnology: true,
    coversThirdParty: true,
  },
  {
    slug: "stock-availability",
    code: "STK_AVL",
    name: "Stock-availability accuracy",
    outcome: "Online stock-availability reflects actual physical inventory; customer orders are reliable.",
    category: "Retail commerce",
    sectors: ["retail-ecommerce"],
    tiers: ["TIER_1", "TIER_2"],
    toleranceMin: 240,
    criticality: "HIGH",
    coversTechnology: true,
    coversDataIntegrity: true,
  },
  {
    slug: "click-and-collect",
    code: "CCK",
    name: "Click-and-collect pickup",
    outcome: "Customers pre-ordering online can collect from the store with no friction.",
    category: "Retail commerce",
    sectors: ["retail-ecommerce"],
    tiers: ["TIER_1", "TIER_2"],
    toleranceMin: 120,
    criticality: "MEDIUM",
    coversTechnology: true,
    coversDataIntegrity: true,
  },
  {
    slug: "loyalty-points",
    code: "LOY_PTS",
    name: "Loyalty-programme points accrual and redemption",
    outcome: "Loyalty customers accrue points on purchases and can redeem them.",
    category: "Retail commerce",
    sectors: ["retail-ecommerce"],
    tiers: ["TIER_1", "TIER_2", "TIER_3"],
    toleranceMin: 1440,
    criticality: "LOW",
    coversTechnology: true,
    coversDataIntegrity: true,
  },

  // ─── Logistics ────────────────────────────────────────────────────────
  {
    slug: "parcel-tracking",
    code: "PCL_TRK",
    name: "Parcel tracking and customer-visibility",
    outcome: "Senders and recipients can track parcels in real time via web / app / SMS.",
    category: "Logistics",
    sectors: ["logistics"],
    tiers: ["TIER_1", "TIER_2"],
    toleranceMin: 240,
    criticality: "MEDIUM",
    coversTechnology: true,
    coversDataIntegrity: true,
  },
  {
    slug: "warehouse-fulfilment",
    code: "WH_FUL",
    name: "Warehouse fulfilment operations",
    outcome: "Orders flow through the WMS, are picked, packed, and ready for dispatch within SLA.",
    category: "Logistics",
    sectors: ["logistics", "retail-ecommerce"],
    tiers: ["TIER_1", "TIER_2"],
    toleranceMin: 120,
    criticality: "HIGH",
    coversTechnology: true,
    coversProperty: true,
    coversPeople: true,
  },
  {
    slug: "final-mile-delivery",
    code: "LM_DEL",
    name: "Final-mile delivery operations",
    outcome: "Drivers complete delivery routes; recipients receive parcels within promised windows.",
    category: "Logistics",
    sectors: ["logistics"],
    tiers: ["TIER_1", "TIER_2"],
    toleranceMin: 720,
    criticality: "HIGH",
    coversPeople: true,
    coversTechnology: true,
    coversThirdParty: true,
  },
  {
    slug: "customs-clearance",
    code: "CUST_CLR",
    name: "Customs declaration and clearance",
    outcome: "Inbound and outbound shipments clear customs; cargo flows uninterrupted.",
    category: "Logistics",
    sectors: ["logistics", "government"],
    tiers: ["TIER_1", "TIER_2"],
    toleranceMin: 240,
    criticality: "HIGH",
    coversTechnology: true,
    coversThirdParty: true,
  },

  // ─── Education delivery ───────────────────────────────────────────────
  {
    slug: "online-teaching-lectures",
    code: "ONL_TCH",
    name: "Online teaching and lectures",
    outcome: "Lectures and seminars run on schedule, accessible to enrolled students.",
    category: "Education delivery",
    sectors: ["higher-ed"],
    tiers: ["TIER_2", "TIER_3"],
    toleranceMin: 240,
    criticality: "HIGH",
    coversTechnology: true,
    coversThirdParty: true,
  },
  {
    slug: "online-assessment",
    code: "ONL_ASS",
    name: "Online assessment and exam-taking",
    outcome: "Students can sit timed online assessments without technical disruption.",
    category: "Education delivery",
    sectors: ["higher-ed"],
    tiers: ["TIER_2", "TIER_3"],
    toleranceMin: 30,
    criticality: "CRITICAL",
    coversTechnology: true,
    coversDataAvailability: true,
    coversDataIntegrity: true,
  },
  {
    slug: "student-records",
    code: "STU_REC",
    name: "Student records and enrolment management",
    outcome: "Student records, enrolment, fee-status and visa-compliance reporting are up to date.",
    category: "Education delivery",
    sectors: ["higher-ed", "government"],
    tiers: ["TIER_2", "TIER_3"],
    toleranceMin: 1440,
    criticality: "HIGH",
    coversTechnology: true,
    coversDataIntegrity: true,
  },
  {
    slug: "research-data-storage",
    code: "RES_DAT",
    name: "Research data storage and backup",
    outcome: "Research data is preserved, accessible and recoverable in line with funder requirements.",
    category: "Education delivery",
    sectors: ["higher-ed"],
    tiers: ["TIER_2", "TIER_3"],
    toleranceMin: 1440,
    criticality: "HIGH",
    coversTechnology: true,
    coversDataIntegrity: true,
    coversDataAvailability: true,
  },

  // ─── Manufacturing ─────────────────────────────────────────────────────
  {
    slug: "production-line-operations",
    code: "PROD_LN",
    name: "Production line operations",
    outcome: "Production lines operate to schedule, output meets quality and quantity targets.",
    category: "Manufacturing",
    sectors: ["manufacturing"],
    tiers: ["TIER_1", "TIER_2"],
    toleranceMin: 240,
    criticality: "CRITICAL",
    coversTechnology: true,
    coversProperty: true,
    coversPeople: true,
    coversThirdParty: true,
  },
  {
    slug: "supply-chain-mgmt",
    code: "SC_MGMT",
    name: "Inbound supply-chain management",
    outcome: "Raw materials and components arrive on schedule to feed production.",
    category: "Manufacturing",
    sectors: ["manufacturing"],
    tiers: ["TIER_1", "TIER_2"],
    toleranceMin: 1440,
    criticality: "HIGH",
    coversTechnology: true,
    coversThirdParty: true,
  },
  {
    slug: "quality-control",
    code: "QC",
    name: "Quality control and inspection",
    outcome: "Products are inspected per quality standards before shipping.",
    category: "Manufacturing",
    sectors: ["manufacturing"],
    tiers: ["TIER_1", "TIER_2"],
    toleranceMin: 480,
    criticality: "HIGH",
    coversTechnology: true,
    coversPeople: true,
    coversDataIntegrity: true,
  },
  {
    slug: "product-recall-mgmt",
    code: "PROD_RCL",
    name: "Product recall management",
    outcome: "When safety defects are identified, the firm can trace affected units and execute recall.",
    category: "Manufacturing",
    sectors: ["manufacturing", "retail-ecommerce"],
    tiers: ["TIER_1", "TIER_2"],
    toleranceMin: 1440,
    criticality: "CRITICAL",
    coversPeople: true,
    coversTechnology: true,
    coversThirdParty: true,
  },

  // ─── Media delivery ───────────────────────────────────────────────────
  {
    slug: "broadcast-playout",
    code: "BCAST_PO",
    name: "Live broadcast playout",
    outcome: "TV / radio channel transmits on schedule without interruption.",
    category: "Media delivery",
    sectors: ["media-broadcasting"],
    tiers: ["TIER_1", "TIER_2"],
    toleranceMin: 15,
    criticality: "CRITICAL",
    coversTechnology: true,
    coversThirdParty: true,
  },
  {
    slug: "streaming-video-delivery",
    code: "STR_VID",
    name: "Streaming video delivery (VOD / live)",
    outcome: "Streaming subscribers can watch content without playback failures.",
    category: "Media delivery",
    sectors: ["media-broadcasting"],
    tiers: ["TIER_1", "TIER_2"],
    toleranceMin: 30,
    criticality: "HIGH",
    coversTechnology: true,
    coversThirdParty: true,
  },
  {
    slug: "newsroom-publication",
    code: "NEWS_PUB",
    name: "Newsroom publication pipeline",
    outcome: "Journalists can research, write and publish stories to the digital and print outlets.",
    category: "Media delivery",
    sectors: ["media-broadcasting"],
    tiers: ["TIER_2", "TIER_3"],
    toleranceMin: 120,
    criticality: "HIGH",
    coversTechnology: true,
    coversDataIntegrity: true,
  },

  // ─── Professional services ────────────────────────────────────────────
  {
    slug: "matter-management",
    code: "MAT_MGT",
    name: "Legal matter management",
    outcome: "Lawyers can open, run and close client matters with full document control and time-recording.",
    category: "Professional services",
    sectors: ["legal-professional"],
    tiers: ["TIER_1", "TIER_2"],
    toleranceMin: 120,
    criticality: "HIGH",
    coversTechnology: true,
    coversDataAvailability: true,
    coversDataIntegrity: true,
  },
  {
    slug: "audit-engagement-mgmt",
    code: "AUD_ENG",
    name: "Audit engagement management",
    outcome: "Audit engagements proceed on schedule with full evidence trail and review.",
    category: "Professional services",
    sectors: ["legal-professional", "asset-wealth"],
    tiers: ["TIER_1", "TIER_2"],
    toleranceMin: 480,
    criticality: "HIGH",
    coversTechnology: true,
    coversDataIntegrity: true,
  },
  {
    slug: "client-document-management",
    code: "CLI_DOC",
    name: "Client document management and privilege",
    outcome: "Client documents are stored, accessible to authorised users only, with privilege preserved.",
    category: "Professional services",
    sectors: ["legal-professional"],
    tiers: ["TIER_1", "TIER_2", "TIER_3"],
    toleranceMin: 240,
    criticality: "HIGH",
    coversTechnology: true,
    coversDataAvailability: true,
    coversDataIntegrity: true,
  },

  // ─── Multi-sector platforms ───────────────────────────────────────────
  {
    slug: "saas-platform-availability",
    code: "SAAS_AVAIL",
    name: "SaaS platform customer-facing availability",
    outcome: "Customers can log in and use the platform within SLA windows.",
    category: "Support",
    sectors: ["technology-saas"],
    tiers: ["TIER_1", "TIER_2", "TIER_3"],
    toleranceMin: 60,
    criticality: "CRITICAL",
    coversTechnology: true,
    coversDataAvailability: true,
    coversThirdParty: true,
  },
  {
    slug: "api-platform",
    code: "API_PLT",
    name: "Public API platform for integrations",
    outcome: "Customer integrations and partner systems can call the public API reliably.",
    category: "Support",
    sectors: ["technology-saas", "payments-fintech"],
    tiers: ["TIER_1", "TIER_2"],
    toleranceMin: 60,
    criticality: "CRITICAL",
    coversTechnology: true,
    coversDataAvailability: true,
  },
  {
    slug: "customer-data-platform",
    code: "CDP",
    name: "Customer data platform / CRM access",
    outcome: "Customer-facing teams (sales, support, ops) can access accurate, current customer data.",
    category: "Support",
    sectors: ["banking", "insurance", "retail-ecommerce", "telecoms", "technology-saas"],
    tiers: ["TIER_1", "TIER_2", "TIER_3"],
    toleranceMin: 240,
    criticality: "HIGH",
    coversTechnology: true,
    coversDataIntegrity: true,
    coversThirdParty: true,
  },

  // ─── Additional payments / fintech IBSs ───────────────────────────────
  {
    slug: "open-banking-payment-initiation",
    code: "OB_PIS",
    name: "Open-banking payment initiation (PISP)",
    outcome: "Merchants and apps can initiate payments from customer bank accounts via open-banking APIs.",
    category: "Payments",
    sectors: ["banking", "payments-fintech"],
    tiers: ["TIER_2", "TIER_3"],
    toleranceMin: 120,
    criticality: "HIGH",
    coversTechnology: true,
    coversThirdParty: true,
    thirdParties: ["CMA9 banks", "OBL"],
  },
  {
    slug: "merchant-acquiring",
    code: "MCH_ACQ",
    name: "Merchant acquiring service",
    outcome: "Merchants can process card payments via the firm's acquiring service.",
    category: "Payments",
    sectors: ["payments-fintech", "retail-ecommerce"],
    tiers: ["TIER_1", "TIER_2"],
    toleranceMin: 60,
    criticality: "CRITICAL",
    coversTechnology: true,
    coversThirdParty: true,
  },
  {
    slug: "fx-conversion",
    code: "FX_CONV",
    name: "FX conversion for cross-border transactions",
    outcome: "Customers can convert currencies and send international payments at quoted rates.",
    category: "Payments",
    sectors: ["payments-fintech", "banking"],
    tiers: ["TIER_2", "TIER_3"],
    toleranceMin: 120,
    criticality: "HIGH",
    coversTechnology: true,
    coversThirdParty: true,
  },
  {
    slug: "crypto-fiat-onramp",
    code: "CRY_RMP",
    name: "Crypto fiat on/off-ramp",
    outcome: "Customers can convert between fiat and crypto assets through the firm's exchange or wallet.",
    category: "Payments",
    sectors: ["payments-fintech"],
    tiers: ["TIER_3"],
    toleranceMin: 240,
    criticality: "MEDIUM",
    coversTechnology: true,
    coversDataIntegrity: true,
    coversThirdParty: true,
  },

  // ─── Additional insurance IBSs ────────────────────────────────────────
  {
    slug: "underwriting-decision",
    code: "UW_DEC",
    name: "Underwriting decision-engine for new policies",
    outcome: "Underwriting decisions are issued for new applications within service-target windows.",
    category: "Insurance",
    sectors: ["insurance"],
    tiers: ["TIER_1", "TIER_2"],
    toleranceMin: 240,
    criticality: "HIGH",
    coversTechnology: true,
    coversDataIntegrity: true,
    coversThirdParty: true,
  },
  {
    slug: "reinsurance-management",
    code: "REINS",
    name: "Reinsurance treaty management and reporting",
    outcome: "Reinsurance treaties are tracked, exposures reported and recoveries processed.",
    category: "Insurance",
    sectors: ["insurance"],
    tiers: ["TIER_1", "TIER_2"],
    toleranceMin: 1440,
    criticality: "HIGH",
    coversTechnology: true,
    coversDataIntegrity: true,
    coversThirdParty: true,
  },
  {
    slug: "actuarial-modelling",
    code: "ACT_MDL",
    name: "Actuarial pricing and capital modelling",
    outcome: "Pricing models and capital calculations are accurate and current for trading decisions and Solvency II.",
    category: "Insurance",
    sectors: ["insurance"],
    tiers: ["TIER_1", "TIER_2"],
    toleranceMin: 4320,
    criticality: "HIGH",
    coversTechnology: true,
    coversDataIntegrity: true,
    coversThirdParty: true,
  },
  {
    slug: "broker-portal-quote",
    code: "BRK_QUOTE",
    name: "Broker portal — quote and bind",
    outcome: "Brokers can quote and bind policies via the digital portal.",
    category: "Insurance",
    sectors: ["insurance"],
    tiers: ["TIER_1", "TIER_2"],
    toleranceMin: 120,
    criticality: "HIGH",
    coversTechnology: true,
    coversThirdParty: true,
  },

  // ─── Additional asset / wealth IBSs ───────────────────────────────────
  {
    slug: "nav-calculation",
    code: "NAV",
    name: "Daily NAV calculation and publication",
    outcome: "Fund NAV is calculated, validated and published by the cut-off so investors and platforms have current pricing.",
    category: "Trading",
    sectors: ["asset-wealth"],
    tiers: ["TIER_1", "TIER_2"],
    toleranceMin: 240,
    criticality: "CRITICAL",
    coversTechnology: true,
    coversDataIntegrity: true,
    coversThirdParty: true,
  },
  {
    slug: "portfolio-rebalancing",
    code: "PORT_REB",
    name: "Model-portfolio rebalancing execution",
    outcome: "Model-portfolio changes are executed across managed portfolios within the trading window.",
    category: "Trading",
    sectors: ["asset-wealth"],
    tiers: ["TIER_1", "TIER_2"],
    toleranceMin: 240,
    criticality: "HIGH",
    coversTechnology: true,
    coversDataIntegrity: true,
  },
  {
    slug: "investor-platform-trading",
    code: "INV_PLT",
    name: "Retail investor platform — trade execution",
    outcome: "Retail customers can place buy / sell orders, see executions and view holdings.",
    category: "Trading",
    sectors: ["asset-wealth"],
    tiers: ["TIER_2", "TIER_3"],
    toleranceMin: 60,
    criticality: "CRITICAL",
    coversTechnology: true,
    coversDataAvailability: true,
  },
  {
    slug: "custody-asset-records",
    code: "CUST_AST",
    name: "Custody asset-record maintenance",
    outcome: "Asset positions held in custody are accurate, reconciled and reportable to investors and regulators.",
    category: "Trading",
    sectors: ["asset-wealth", "banking"],
    tiers: ["TIER_1", "TIER_2"],
    toleranceMin: 480,
    criticality: "CRITICAL",
    coversTechnology: true,
    coversDataIntegrity: true,
    coversThirdParty: true,
  },

  // ─── Cross-cutting horizontal IBSs ────────────────────────────────────
  {
    slug: "identity-and-access",
    code: "IDAM",
    name: "Identity and access management for staff",
    outcome: "Staff can log into systems they need; identity is provisioned and de-provisioned correctly.",
    category: "Support",
    sectors: ["banking", "insurance", "asset-wealth", "payments-fintech", "telecoms", "energy-utilities", "retail-ecommerce", "healthcare", "government", "aviation-transport", "logistics", "media-broadcasting", "higher-ed", "manufacturing", "technology-saas", "legal-professional"],
    tiers: ["TIER_1", "TIER_2", "TIER_3"],
    toleranceMin: 60,
    criticality: "CRITICAL",
    coversTechnology: true,
    coversPeople: true,
    coversDataIntegrity: true,
  },
  {
    slug: "email-and-collaboration",
    code: "EMAIL_COL",
    name: "Email and collaboration services",
    outcome: "Staff can send and receive email, access shared calendars and collaborate on documents.",
    category: "Support",
    sectors: ["banking", "insurance", "asset-wealth", "payments-fintech", "telecoms", "energy-utilities", "retail-ecommerce", "healthcare", "government", "aviation-transport", "logistics", "media-broadcasting", "higher-ed", "manufacturing", "technology-saas", "legal-professional"],
    tiers: ["TIER_1", "TIER_2", "TIER_3"],
    toleranceMin: 240,
    criticality: "HIGH",
    coversTechnology: true,
    coversThirdParty: true,
  },
  {
    slug: "regulatory-reporting",
    code: "REG_RPT",
    name: "Regulatory reporting submissions",
    outcome: "Statutory regulatory reports are submitted on time, complete and accurate.",
    category: "Support",
    sectors: ["banking", "insurance", "asset-wealth", "payments-fintech", "telecoms", "energy-utilities", "government", "healthcare"],
    tiers: ["TIER_1", "TIER_2"],
    toleranceMin: 1440,
    criticality: "HIGH",
    coversTechnology: true,
    coversDataIntegrity: true,
  },
  {
    slug: "payroll-processing",
    code: "PAYROLL",
    name: "Staff payroll processing",
    outcome: "Staff are paid the correct amount on the correct date.",
    category: "Support",
    sectors: ["banking", "insurance", "asset-wealth", "payments-fintech", "telecoms", "energy-utilities", "retail-ecommerce", "healthcare", "government", "aviation-transport", "logistics", "media-broadcasting", "higher-ed", "manufacturing", "technology-saas", "legal-professional"],
    tiers: ["TIER_1", "TIER_2", "TIER_3"],
    toleranceMin: 4320,
    criticality: "HIGH",
    coversTechnology: true,
    coversDataIntegrity: true,
    coversThirdParty: true,
  },
  {
    slug: "cyber-incident-response",
    code: "CYB_IR",
    name: "Cyber-incident response capability",
    outcome: "Security incidents are detected, contained, eradicated and recovered from within target windows.",
    category: "Support",
    sectors: ["banking", "insurance", "asset-wealth", "payments-fintech", "telecoms", "energy-utilities", "retail-ecommerce", "healthcare", "government", "aviation-transport", "logistics", "media-broadcasting", "higher-ed", "manufacturing", "technology-saas", "legal-professional"],
    tiers: ["TIER_1", "TIER_2"],
    toleranceMin: 60,
    criticality: "CRITICAL",
    coversTechnology: true,
    coversPeople: true,
    coversDataIntegrity: true,
    coversThirdParty: true,
  },
  {
    slug: "physical-site-access",
    code: "SITE_ACC",
    name: "Physical site access control",
    outcome: "Staff and authorised visitors can access offices, plants and operational sites; unauthorised people cannot.",
    category: "Support",
    sectors: ["banking", "insurance", "asset-wealth", "energy-utilities", "retail-ecommerce", "healthcare", "government", "aviation-transport", "logistics", "manufacturing", "higher-ed"],
    tiers: ["TIER_1", "TIER_2", "TIER_3"],
    toleranceMin: 120,
    criticality: "HIGH",
    coversPeople: true,
    coversProperty: true,
    coversTechnology: true,
  },
];

/** Heuristic — surface the "best matches" for a firm tier first. */
export function relevanceScore(ibs: LibraryIBS, orgTier: FirmTier | null): number {
  if (!orgTier) return 0;
  if (ibs.tiers.includes(orgTier)) return 0; // top
  return 1;
}
