/**
 * FCA / PRA Material Third Party Annex 3 controlled vocabularies.
 *
 * Extracted from the official Annex 3 register + notification XLSX templates
 * (Taxonomies_Register sheet). When the regulator publishes a new revision,
 * regenerate by re-extracting from the XLSX into the SERVICE_TYPE,
 * FUNCTION_CATEGORY and COUNTRY arrays below.
 *
 * Generated 2026-05-18 from ps26-2-third-party-register-template-annex-3.xlsx.
 */

export const SERVICE_TYPE = [
  "Access to external providers (e.g., stock exchanges)",
  "Data Analytics",
  "App Modernisation",
  "Application integration & management",
  "Artificial intelligence & machine learning",
  "Backup and Disaster Recovery",
  "Compliance",
  "Compute",
  "Containers",
  "Cost controls",
  "Database",
  "Developer Tools",
  "Enterprise",
  "Hardware and physical",
  "IaaS (Infrastructure)",
  "ICT Consulting",
  "ICT project management",
  "ICT Risk management",
  "ICT, facilities and hosting services (excluding Cloud services)",
  "Integration Services",
  "Internet of Things",
  "Management and governance",
  "Migration",
  "Networking & Operations",
  "Non-Cloud Data storage",
  "Optimisation",
  "PaaS (Platform)",
  "Processing",
  "Provision of data",
  "QaaS (Quantum)",
  "SaaS (Software)",
  "Security & Identity",
  "Serverless",
  "Software (open source etc)",
  "Software licencing",
  "Storage",
  "Telecom carrier",
  "Other",
] as const;

export const FUNCTION_CATEGORY = [
  "BF: Benchmark Activities: Providing data in relation to a regulated Benchmark",
  "BF: Benchmark Activities: Management of recognised Benchmark Activities",
  "BF: Benchmark Activities: Administering a Benchmark",
  "BF: Capital Markets & Investment: Asset management such as activities related to Recognised Investment Exchanges",
  "BF: Capital Markets & Investment: Derivatives such as debenture trading",
  "BF: Capital Markets & Investment: Trading portfolio such as credit broking and trading activities",
  "BF: Clearing, Custody & Settlement: Custody services",
  "BF: Clearing, Custody & Settlement: Settlement services",
  "BF: Clearing, Custody & Settlement: Third-party operational services",
  "BF: Clearing, Custody & Settlements: Asset servicing such as trading securities",
  "BF: Clearing, Custody & Settlements: Cash such as commodity option and future",
  "BF: Clearing, Custody & Settlements: Collateral mgmt. such as buy, sell or store crypto assets",
  "BF: Clearing, Custody & Settlements: Corporate trust services",
  "BF: Clearing, Custody & Settlements: Debt",
  "BF: Clearing, Custody & Settlements: Delegated, sub-custody",
  "BF: Clearing, Custody & Settlements: Derivatives (ETD, OTC Clear, Bilat)",
  "BF: Clearing, Custody & Settlements: Equities",
  "BF: Clearing, Custody & Settlements: FMI access for financial 3rd parties",
  "BF: Clearing, Custody & Settlements: FX",
  "BF: Clearing, Custody & Settlements: Money markets",
  "BF: Clearing, Custody & Settlements: Omnibus Acts",
  "BF: Clearing, Custody & Settlements: Primary",
  "BF: Clearing, Custody & Settlements: Safekeeping",
  "BF: Clearing, Custody & Settlements: Treasury, cash mgmt services",
  "BF: Credit Rating Agencies",
  "BF: Deposit Taking & Savings: Certificates of deposit",
  "BF: Deposit Taking & Savings: Corporate deposits",
  "BF: Deposit Taking & Savings: Retail current accounts",
  "BF: Deposit Taking & Savings: Retail savings accounts, time accounts",
  "BF: Deposit Taking & Savings: SME current accounts",
  "BF: Deposit Taking & Savings: SME savings accounts",
  "BF: FX swaps",
  "BF: Insurance: Administrative services",
  "BF: Insurance: Claims processing",
  "BF: Insurance: Premium collection",
  "BF: Insurance: Pricing",
  "BF: Investment funds services",
  "BF: Lending & Loan Servicing: Corporate lending",
  "BF: Lending & Loan Servicing: Credit card merchant services",
  "BF: Lending & Loan Servicing: Infrastructure lending",
  "BF: Lending & Loan Servicing: Leasing",
  "BF: Lending & Loan Servicing: Project finance",
  "BF: Lending & Loan Servicing: Retail credit cards",
  "BF: Lending & Loan Servicing: Retail mortgages, other secured (Auto)",
  "BF: Lending & Loan Servicing: Retail unsecured personal lending",
  "BF: Lending & Loan Servicing: SME lending (secured)",
  "BF: Lending & Loan Servicing: Trade finance",
  "BF: Payments: Lockbox services",
  "BF: Payments: Merchant card services",
  "BF: Payments: Single currency, FX",
  "BF: Payments: Third-party operational services",
  "BF: Payments: Wire transfers",
  "BF: Payments: Cash services",
  "BF: Payments: Payment services",
  "BF: Payments: Settlement Services",
  "BF: Repo",
  "BF: Wholesale Funding Markets: Securities financing",
  "BF: Wholesale Funding Markets: Securities lending",
  "BF: Wholesale Funding Markets: Wholesale lending, borrowing",
  "CF: Treasury/ALM services",
  "CF: Human resources",
  "CF: Information Technology",
  "CF: Real estate provision or management",
  "CF: Legal services/compliance",
  "CF: Finance/Accounting",
  "CF: Operations/Transaction processing",
  "CF: Risk Management",
  "CF: Enterprise: Most functions or IBSs within the organisation",
  "Other",
] as const;

export const COUNTRY = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "American Samoa",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antarctica",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Aruba",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas (the)",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bermuda",
  "Åland Islands",
  "Bhutan",
  "Bolivia (Plurinational State of)",
  "Bonaire, Sint Eustatius and Saba",
  "Bosnia and Herzegovina",
  "Botswana",
  "Bouvet Island",
  "Brazil",
  "British Indian Ocean Territory (the)",
  "Brunei Darussalam",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Cayman Islands (the)",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Christmas Island",
  "Cocos (Keeling) Islands (the)",
  "Colombia",
  "Comoros (the)",
  "Congo (the Democratic Republic of the)",
  "Congo (the)",
  "Cook Islands (the)",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Curaçao",
  "Cyprus",
  "Czechia",
  "Côte d'Ivoire",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic (the)",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Falkland Islands (the) [Malvinas]",
  "Faroe Islands (the)",
  "Fiji",
  "Finland",
  "France",
  "French Guiana",
  "French Polynesia",
  "French Southern Territories (the)",
  "Gabon",
  "Gambia (the)",
  "Georgia",
  "Germany",
  "Ghana",
  "Gibraltar",
  "Greece",
  "Greenland",
  "Grenada",
  "Guadeloupe",
  "Guam",
  "Guatemala",
  "Guernsey",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Heard Island and McDonald Islands",
  "Holy See (the)",
  "Honduras",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran (Islamic Republic of)",
  "Iraq",
  "Ireland",
  "Isle of Man",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jersey",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Korea (the Democratic People's Republic of)",
  "Korea (the Republic of)",
  "Kuwait",
  "Kyrgyzstan",
  "Lao People's Democratic Republic (the)",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macao",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands (the)",
  "Martinique",
  "Mauritania",
  "Mauritius",
  "Mayotte",
  "Mexico",
  "Micronesia (Federated States of)",
  "Moldova (the Republic of)",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Montserrat",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands (Kingdom of the)",
  "New Caledonia",
  "New Zealand",
  "Nicaragua",
  "Niger (the)",
  "Nigeria",
  "Niue",
  "Norfolk Island",
  "North Macedonia",
  "Northern Mariana Islands (the)",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine, State of",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines (the)",
  "Pitcairn",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Romania",
  "Russia Federation (the)",
  "Rwanda",
  "Réunion",
  "Saint Barthélemy",
  "Saint Helena, Ascension and Tristan da Cunha",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Martin (French part)",
  "Saint Pierre and Miquelon",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Sint Maarten (Dutch part)",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Georgia and the South Sandwich Islands",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan (the)",
  "Suriname",
  "Svalbard and Jan Mayen",
  "Sweden",
  "Switzerland",
  "Syrian Arab Republic (the)",
  "Taiwan (Province of China)",
  "Tajikistan",
  "Tanzania, the United Republic of",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tokelau",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkmenistan",
  "Turks and Caicos Islands (the)",
  "Tuvalu",
  "Turkiye",
  "Uganda",
  "Ukraine",
  "United Arab Emirates (the)",
  "United Kingdom of Great Britain and Northern Ireland (the)",
  "United States Minor Outlying Islands (the)",
  "United States of America (the)",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Venezuela (Bolivarian Republic of)",
  "Viet Nam",
  "Virgin Islands (British)",
  "Virgin Islands (U.S.)",
  "Wallis and Futuna",
  "Western Sahara*",
  "Yemen",
  "Zambia",
  "Zimbabwe",
] as const;


export type ServiceTypeValue = (typeof SERVICE_TYPE)[number];
export type FunctionCategoryValue = (typeof FUNCTION_CATEGORY)[number];
export type CountryValue = (typeof COUNTRY)[number];

/** Label maps for our enums → official regulator dropdown strings.
 *  Used by the XLSX generator (Commits C and D) so the output matches the
 *  template's "Formatted data" sheet expectations exactly. */

export const MATERIALITY_REASON_LABEL: Record<string, string> = {
  CRITICAL_OPERATIONAL_FUNCTION: "Service involves a critical operational function",
  SUPPORTS_IMPORTANT_BUSINESS_SERVICE: "Service involves an Important Business Service",
  CRITICAL_DATA_ACCESS: "Service involves critical data access or processing",
  LARGE_FINANCIAL_VALUE: "Large financial value / annual contract value",
  HIGH_SUBSTITUTION_COMPLEXITY: "Highly complex substitution",
  CONCENTRATION_RISK: "Concentration risk",
  CYBER_THREAT_EXPOSURE: "Cyber threat exposure",
  CROSS_BORDER_DATA_FLOW: "Cross-border data flow",
  FOURTH_PARTY_DEPENDENCY: "Significant fourth-party dependency",
  REGULATED_ACTIVITY_DELEGATION: "Service involves an entire regulated activity",
  OTHER: "Other",
};

export const CLOUD_DEPLOYMENT_LABEL: Record<string, string> = {
  PUBLIC: "Public",
  PRIVATE: "Private",
  HYBRID: "Hybrid",
  NON_CLOUD: "Non-cloud",
};

export const SUBSTITUTABILITY_LABEL: Record<string, string> = {
  EASILY_SUBSTITUTABLE: "Easily substitutable",
  HIGHLY_COMPLEX_SUBSTITUTABILITY: "Highly complex substitutability",
  NOT_SUBSTITUTABLE: "Not substitutable",
};

export const REINTEGRATION_LABEL: Record<string, string> = {
  EASY: "Easy",
  DIFFICULT: "Difficult",
  IMPOSSIBLE: "Impossible",
};

export const IMPACT_DISCONTINUE_LABEL: Record<string, string> = {
  LOW: "Low",
  MEDIUM: "Medium",
  HIGH: "High",
};

export const ASSESSMENT_OUTCOME_LABEL: Record<string, string> = {
  SATISFACTORY: "Satisfactory",
  NON_SATISFACTORY: "Non-satisfactory",
  ONGOING: "Ongoing",
  NOT_APPLICABLE: "N/A",
};

export const COMPLIANCE_LABEL: Record<string, string> = {
  YES: "Yes",
  NO: "No",
  ONGOING: "Ongoing",
};

export const ASSESSMENT_KIND_LABEL: Record<string, string> = {
  RISK: "Risk assessment",
  AUDIT: "Audit",
  FINANCIAL_DD: "Financial due diligence",
  CYBER_DD: "Cyber due diligence",
};

export const MTP_SUBMISSION_TYPE_LABEL: Record<string, string> = {
  NEW_CONTRACT: "New contract",
  CONTRACT_CHANGE: "Contract change",
  CONTRACT_RENEWAL: "Contract renewal",
  CONTRACT_EXIT: "Contract exit",
  CONTRACT_BREACH: "Contract breach",
  MATERIAL_INCIDENT: "Material incident",
};

/** Best-effort coarse FunctionCategory enum → the regulator fine-grained label
 *  pick. Used as the *default* when a vendor has an enum-level category but
 *  hasn't been mapped to a specific taxonomy string yet. UI should still
 *  let the user pick the exact taxonomy string. */
export const FUNCTION_CATEGORY_FALLBACK: Record<string, FunctionCategoryValue> = {
  BANKING_FUNCTIONS: "BF: Deposit Taking & Savings: Retail current accounts",
  PAYMENTS: "BF: Payments: Wire transfers",
  CLEARING_SETTLEMENT: "BF: Clearing, Custody & Settlement: Settlement services",
  TRADING_INVESTMENT: "BF: Capital Markets & Investment: Trading portfolio such as credit broking and trading activities",
  CUSTOMER_SERVICING: "Other",
  DATA_ANALYTICS: "Other",
  INFORMATION_TECHNOLOGY: "Other",
  CLOUD_INFRASTRUCTURE: "Other",
  CYBER_SECURITY: "Other",
  HR_LEGAL_PROFESSIONAL: "Other",
  OUTSOURCED_OPERATIONS: "Other",
  BENCHMARK_ACTIVITIES: "BF: Benchmark Activities: Providing data in relation to a regulated Benchmark",
  OTHER: "Other",
};
