import type { VendorTier } from "@/generated/prisma/enums";
import type { Sector } from "@/lib/library/sectors";

/**
 * Pre-built vendor library — opinionated catalogue of vendors active in
 * UK financial services, energy, telecoms, healthcare, retail, public
 * sector, manufacturing, and adjacent industries. Drives the LibraryBrowser
 * drawer launched from /vendors so admins can one-click-add real providers
 * instead of typing them.
 *
 * Each entry mirrors the Vendor model shape; fields beyond name +
 * service-kind + suggested tier are best-effort defaults you'd want to
 * refine post-add (contract dates, assurance, exit plan). DORA-critical
 * is marked true for tier-1 financial-services rails and core providers.
 *
 * `sectors` tag(s) drive the cross-sector filter on the library grid.
 */

export type LibraryVendor = {
  slug: string;
  name: string;
  serviceKind: string;
  category: VendorCategory;
  description: string;
  suggestedTier: VendorTier;
  isDoraCritical: boolean;
  /** One or more sectors this vendor commonly serves. */
  sectors?: Sector[];
  hyperscaler?: string;
  region?: string;
  /** Industry-typical assurance — admins refine to the specific report. */
  assuranceKind?: "SOC2_TYPE_2" | "SOC2_TYPE_1" | "ISAE3402" | "ISO27001";
  statusUrl?: string;
};

export const VENDOR_CATEGORIES = [
  // Banking & financial services
  "Core banking",
  "Payments",
  "Card issuing",
  "Open banking",
  "KYC / Identity",
  "AML / Sanctions",
  "Fraud",
  "Reconciliations",
  "Documents & e-sign",
  "Cloud & infra",
  "Communications",
  "Customer & CRM",
  "Treasury",
  // Cross-sector
  "Energy & utilities",
  "Telecoms infra",
  "Healthcare IT",
  "Retail & ecommerce",
  "Transport & travel",
  "Logistics & shipping",
  "Government IT",
  "Education tech",
  "Media & broadcast",
  "Manufacturing & industrial",
  "Cybersecurity",
  "Productivity & HR",
] as const;

export type VendorCategory = (typeof VENDOR_CATEGORIES)[number];

export const VENDOR_LIBRARY: LibraryVendor[] = [
  // ─── Core banking ─────────────────────────────────────────────────────
  {
    slug: "thought-machine",
    name: "Thought Machine",
    serviceKind: "Cloud-native core banking (Vault)",
    category: "Core banking",
    sectors: ["banking"],
    description:
      "Smart-contract-based core banking ledger. Used by Lloyds, Standard Chartered, JP Morgan and Atom Bank.",
    suggestedTier: "TIER_1",
    isDoraCritical: true,
    hyperscaler: "GCP",
    assuranceKind: "SOC2_TYPE_2",
    statusUrl: "https://status.thoughtmachine.io",
  },
  {
    slug: "mambu",
    name: "Mambu",
    serviceKind: "SaaS composable core banking",
    category: "Core banking",
    sectors: ["banking"],
    description:
      "Cloud banking platform used by digital-first banks (N26, OakNorth, Western Union). Multi-product ledger.",
    suggestedTier: "TIER_1",
    isDoraCritical: true,
    hyperscaler: "AWS",
  },
  {
    slug: "temenos",
    name: "Temenos",
    serviceKind: "Core banking suite (Transact, Infinity)",
    category: "Core banking",
    sectors: ["banking"],
    description:
      "Established core banking provider with deep functional coverage; multi-deployment (on-prem, SaaS, cloud).",
    suggestedTier: "TIER_1",
    isDoraCritical: true,
  },
  {
    slug: "10x-banking",
    name: "10x Banking",
    serviceKind: "Cloud-native banking platform",
    category: "Core banking",
    sectors: ["banking"],
    description:
      "UK-built next-gen banking platform; powers Westpac Australia and Chase UK. Real-time ledger.",
    suggestedTier: "TIER_1",
    isDoraCritical: true,
    hyperscaler: "AWS",
  },
  {
    slug: "tuum",
    name: "Tuum",
    serviceKind: "Modular core banking",
    category: "Core banking",
    sectors: ["banking"],
    description: "Estonian core banking platform; modular product suite, EU/UK focus.",
    suggestedTier: "TIER_1",
    isDoraCritical: true,
  },
  {
    slug: "finastra",
    name: "Finastra",
    serviceKind: "Banking & trade-finance platform",
    category: "Core banking",
    sectors: ["banking"],
    description: "Global financial software — Fusion suite for banking, trade, lending and treasury.",
    suggestedTier: "TIER_1",
    isDoraCritical: true,
  },
  {
    slug: "pismo",
    name: "Pismo",
    serviceKind: "Cloud-native processing platform",
    category: "Core banking",
    sectors: ["banking"],
    description: "Brazilian-origin processing platform; cards + core banking, owned by Visa.",
    suggestedTier: "TIER_2",
    isDoraCritical: false,
    hyperscaler: "AWS",
  },

  // ─── Payments ─────────────────────────────────────────────────────────
  {
    slug: "clearbank",
    name: "ClearBank",
    serviceKind: "Agency banking / Faster Payments / CHAPS",
    category: "Payments",
    sectors: ["banking", "payments-fintech"],
    description:
      "UK agency clearing bank — direct Faster Payments, BACS and CHAPS access for non-clearing fintechs.",
    suggestedTier: "TIER_1",
    isDoraCritical: true,
    assuranceKind: "ISAE3402",
  },
  {
    slug: "modulr",
    name: "Modulr",
    serviceKind: "Embedded payments + accounts API",
    category: "Payments",
    sectors: ["banking", "payments-fintech"],
    description:
      "FCA-regulated payments infrastructure — Faster Payments, BACS, SEPA, virtual accounts. UK + Europe.",
    suggestedTier: "TIER_2",
    isDoraCritical: true,
    hyperscaler: "AWS",
  },
  {
    slug: "form3",
    name: "Form3",
    serviceKind: "Cloud-native payments processing",
    category: "Payments",
    sectors: ["banking", "payments-fintech"],
    description: "API-first payments processor for FPS, BACS, SEPA Inst, CHAPS. Used by Goldman Sachs, Nationwide.",
    suggestedTier: "TIER_1",
    isDoraCritical: true,
  },
  {
    slug: "stripe",
    name: "Stripe",
    serviceKind: "Card acquiring + payments platform",
    category: "Payments",
    sectors: ["banking", "payments-fintech"],
    description: "Global card acquirer + payments orchestration. Wide-ranging product surface.",
    suggestedTier: "TIER_1",
    isDoraCritical: false,
    hyperscaler: "AWS",
    assuranceKind: "SOC2_TYPE_2",
    statusUrl: "https://status.stripe.com",
  },
  {
    slug: "adyen",
    name: "Adyen",
    serviceKind: "Unified commerce + acquiring",
    category: "Payments",
    sectors: ["banking", "payments-fintech"],
    description: "Global acquirer with EU banking licence; multi-channel (online, in-store, embedded).",
    suggestedTier: "TIER_1",
    isDoraCritical: false,
  },
  {
    slug: "gocardless",
    name: "GoCardless",
    serviceKind: "Direct-debit collections",
    category: "Payments",
    sectors: ["banking", "payments-fintech"],
    description: "Recurring payments collection across BACS / SEPA / ACH. UK-headquartered.",
    suggestedTier: "TIER_2",
    isDoraCritical: false,
    hyperscaler: "AWS",
  },
  {
    slug: "swift",
    name: "SWIFT",
    serviceKind: "International payments messaging",
    category: "Payments",
    sectors: ["banking", "payments-fintech"],
    description: "Global financial-messaging network. Underpins international correspondent banking.",
    suggestedTier: "TIER_1",
    isDoraCritical: true,
    assuranceKind: "ISAE3402",
  },
  {
    slug: "pay-uk-fps",
    name: "Pay.UK / FPS",
    serviceKind: "Faster Payments scheme operator",
    category: "Payments",
    sectors: ["banking", "payments-fintech"],
    description: "UK retail payments operator — Faster Payments Service, BACS, Cheque Image Clearing.",
    suggestedTier: "TIER_1",
    isDoraCritical: true,
  },
  {
    slug: "visa",
    name: "Visa",
    serviceKind: "Card network",
    category: "Payments",
    sectors: ["banking", "payments-fintech"],
    description: "Global card network — auth, clearing, settlement.",
    suggestedTier: "TIER_1",
    isDoraCritical: true,
  },
  {
    slug: "mastercard",
    name: "Mastercard",
    serviceKind: "Card network",
    category: "Payments",
    sectors: ["banking", "payments-fintech"],
    description: "Global card network — auth, clearing, settlement.",
    suggestedTier: "TIER_1",
    isDoraCritical: true,
  },

  // ─── Card issuing ─────────────────────────────────────────────────────
  {
    slug: "marqeta",
    name: "Marqeta",
    serviceKind: "Modern card issuing",
    category: "Card issuing",
    sectors: ["banking", "payments-fintech"],
    description: "Open-API card issuing — used by Klarna, Revolut, Affirm.",
    suggestedTier: "TIER_1",
    isDoraCritical: true,
    hyperscaler: "AWS",
  },
  {
    slug: "enfuce",
    name: "Enfuce",
    serviceKind: "Card issuing + processing",
    category: "Card issuing",
    sectors: ["banking", "payments-fintech"],
    description: "EU card-issuing fintech; commonly used by mid-market issuers in the Nordics.",
    suggestedTier: "TIER_2",
    isDoraCritical: false,
  },
  {
    slug: "stripe-issuing",
    name: "Stripe Issuing",
    serviceKind: "Card issuing",
    category: "Card issuing",
    sectors: ["banking", "payments-fintech"],
    description: "Programmatic virtual + physical card issuing via Stripe.",
    suggestedTier: "TIER_2",
    isDoraCritical: false,
    hyperscaler: "AWS",
  },

  // ─── Open banking ─────────────────────────────────────────────────────
  {
    slug: "truelayer",
    name: "TrueLayer",
    serviceKind: "Open Banking payments + data",
    category: "Open banking",
    sectors: ["banking", "payments-fintech"],
    description: "UK-leading PSD2 / Open Banking API — payments + account data aggregation.",
    suggestedTier: "TIER_2",
    isDoraCritical: false,
    hyperscaler: "AWS",
  },
  {
    slug: "tink",
    name: "Tink",
    serviceKind: "Open Banking platform (EU)",
    category: "Open banking",
    sectors: ["banking", "payments-fintech"],
    description: "Swedish-origin Open Banking aggregator now owned by Visa.",
    suggestedTier: "TIER_2",
    isDoraCritical: false,
  },
  {
    slug: "plaid",
    name: "Plaid",
    serviceKind: "Financial data network",
    category: "Open banking",
    sectors: ["banking", "payments-fintech"],
    description: "Account aggregation + data network — global presence, big in US, growing in EU/UK.",
    suggestedTier: "TIER_2",
    isDoraCritical: false,
  },
  {
    slug: "yapily",
    name: "Yapily",
    serviceKind: "Headless Open Banking API",
    category: "Open banking",
    sectors: ["banking", "payments-fintech"],
    description: "API-only Open Banking provider; used by fintechs needing a clean infra layer.",
    suggestedTier: "TIER_2",
    isDoraCritical: false,
  },

  // ─── KYC / Identity ───────────────────────────────────────────────────
  {
    slug: "onfido",
    name: "Onfido",
    serviceKind: "Identity verification (KYC / IDV)",
    category: "KYC / Identity",
    sectors: ["banking", "payments-fintech", "insurance"],
    description: "UK-built ID&V — document scan + selfie biometrics + liveness. Used by Revolut, Monzo and many more.",
    suggestedTier: "TIER_2",
    isDoraCritical: false,
    hyperscaler: "AWS",
    region: "eu-west-1",
  },
  {
    slug: "sumsub",
    name: "Sumsub",
    serviceKind: "KYC / KYB / transaction monitoring",
    category: "KYC / Identity",
    sectors: ["banking", "payments-fintech", "insurance"],
    description: "All-in-one verification platform — KYC, KYB and ongoing monitoring.",
    suggestedTier: "TIER_2",
    isDoraCritical: false,
  },
  {
    slug: "veriff",
    name: "Veriff",
    serviceKind: "Identity verification",
    category: "KYC / Identity",
    sectors: ["banking", "payments-fintech", "insurance"],
    description: "Estonian-built IDV with broad document and language coverage.",
    suggestedTier: "TIER_2",
    isDoraCritical: false,
  },
  {
    slug: "jumio",
    name: "Jumio",
    serviceKind: "Identity verification",
    category: "KYC / Identity",
    sectors: ["banking", "payments-fintech", "insurance"],
    description: "Established AI-powered IDV with broad global presence.",
    suggestedTier: "TIER_2",
    isDoraCritical: false,
  },

  // ─── AML / Sanctions ──────────────────────────────────────────────────
  {
    slug: "complyadvantage",
    name: "ComplyAdvantage",
    serviceKind: "AML screening + transaction monitoring",
    category: "AML / Sanctions",
    sectors: ["banking", "payments-fintech", "asset-wealth"],
    description: "UK-built financial-crime risk data + transaction monitoring.",
    suggestedTier: "TIER_2",
    isDoraCritical: false,
  },
  {
    slug: "refinitiv-world-check",
    name: "Refinitiv World-Check",
    serviceKind: "Sanctions + PEP screening",
    category: "AML / Sanctions",
    sectors: ["banking", "payments-fintech", "asset-wealth"],
    description: "Industry-standard sanctions + PEP + adverse-media data feed.",
    suggestedTier: "TIER_2",
    isDoraCritical: false,
  },
  {
    slug: "nice-actimize",
    name: "NICE Actimize",
    serviceKind: "AML + financial-crime suite",
    category: "AML / Sanctions",
    sectors: ["banking", "payments-fintech", "asset-wealth"],
    description: "Tier-1 AML + fraud detection suite used by large banks.",
    suggestedTier: "TIER_1",
    isDoraCritical: true,
  },
  {
    slug: "quantexa",
    name: "Quantexa",
    serviceKind: "Entity-resolution + financial-crime",
    category: "AML / Sanctions",
    sectors: ["banking", "payments-fintech", "asset-wealth"],
    description: "UK-headquartered entity-resolution + graph analytics; widely used in tier-1 banks.",
    suggestedTier: "TIER_1",
    isDoraCritical: false,
  },

  // ─── Fraud ────────────────────────────────────────────────────────────
  {
    slug: "featurespace",
    name: "Featurespace",
    serviceKind: "Real-time fraud + AML decisioning",
    category: "Fraud",
    sectors: ["banking", "payments-fintech", "insurance", "retail-ecommerce"],
    description: "UK-built ARIC platform — used by HSBC, NatWest, TSB.",
    suggestedTier: "TIER_1",
    isDoraCritical: true,
  },
  {
    slug: "forter",
    name: "Forter",
    serviceKind: "E-commerce fraud detection",
    category: "Fraud",
    sectors: ["banking", "payments-fintech", "insurance", "retail-ecommerce"],
    description: "Real-time fraud-prevention platform for digital commerce.",
    suggestedTier: "TIER_2",
    isDoraCritical: false,
  },

  // ─── Reconciliations ──────────────────────────────────────────────────
  {
    slug: "duco",
    name: "Duco",
    serviceKind: "Data reconciliation",
    category: "Reconciliations",
    sectors: ["banking", "payments-fintech", "asset-wealth"],
    description: "Self-service reconciliation platform — used widely in capital markets and treasury.",
    suggestedTier: "TIER_2",
    isDoraCritical: false,
  },
  {
    slug: "autorek",
    name: "AutoRek",
    serviceKind: "Financial reconciliation + reporting",
    category: "Reconciliations",
    sectors: ["banking", "payments-fintech", "asset-wealth"],
    description: "UK-built reconciliations + regulatory reporting (CASS, FRC) platform.",
    suggestedTier: "TIER_2",
    isDoraCritical: false,
  },
  {
    slug: "smartstream",
    name: "SmartStream",
    serviceKind: "Reconciliation + reference data",
    category: "Reconciliations",
    sectors: ["banking", "payments-fintech", "asset-wealth"],
    description: "Enterprise TLM reconciliations + reference-data utilities.",
    suggestedTier: "TIER_1",
    isDoraCritical: false,
  },

  // ─── Documents & e-sign ───────────────────────────────────────────────
  {
    slug: "docusign",
    name: "DocuSign",
    serviceKind: "E-signature + agreement",
    category: "Documents & e-sign",
    sectors: ["banking", "insurance", "asset-wealth", "legal-professional", "government"],
    description: "Industry-standard e-signature + agreement cloud.",
    suggestedTier: "TIER_3",
    isDoraCritical: false,
    statusUrl: "https://status.docusign.com",
  },
  {
    slug: "adobe-sign",
    name: "Adobe Sign",
    serviceKind: "E-signature",
    category: "Documents & e-sign",
    sectors: ["banking", "insurance", "asset-wealth", "legal-professional", "government"],
    description: "Adobe's e-signature offering; popular in regulated workflows.",
    suggestedTier: "TIER_3",
    isDoraCritical: false,
  },

  // ─── Cloud & infra ────────────────────────────────────────────────────
  {
    slug: "aws",
    name: "AWS",
    serviceKind: "Hyperscaler cloud platform",
    category: "Cloud & infra",
    sectors: ["banking", "insurance", "asset-wealth", "payments-fintech", "telecoms", "energy-utilities", "retail-ecommerce", "healthcare", "government", "aviation-transport", "logistics", "media-broadcasting", "higher-ed", "manufacturing", "technology-saas", "legal-professional"],
    description: "Amazon Web Services — most-common bank/fintech hyperscaler in the UK.",
    suggestedTier: "TIER_1",
    isDoraCritical: true,
    hyperscaler: "AWS",
    region: "eu-west-2",
    assuranceKind: "SOC2_TYPE_2",
    statusUrl: "https://health.aws.amazon.com/health/status",
  },
  {
    slug: "azure",
    name: "Microsoft Azure",
    serviceKind: "Hyperscaler cloud platform",
    category: "Cloud & infra",
    sectors: ["banking", "insurance", "asset-wealth", "payments-fintech", "telecoms", "energy-utilities", "retail-ecommerce", "healthcare", "government", "aviation-transport", "logistics", "media-broadcasting", "higher-ed", "manufacturing", "technology-saas", "legal-professional"],
    description: "Microsoft Azure — common in insurer and enterprise banking estates.",
    suggestedTier: "TIER_1",
    isDoraCritical: true,
    hyperscaler: "Azure",
    region: "uksouth",
    assuranceKind: "SOC2_TYPE_2",
    statusUrl: "https://status.azure.com",
  },
  {
    slug: "gcp",
    name: "Google Cloud (GCP)",
    serviceKind: "Hyperscaler cloud platform",
    category: "Cloud & infra",
    sectors: ["banking", "insurance", "asset-wealth", "payments-fintech", "telecoms", "energy-utilities", "retail-ecommerce", "healthcare", "government", "aviation-transport", "logistics", "media-broadcasting", "higher-ed", "manufacturing", "technology-saas", "legal-professional"],
    description: "Google Cloud — strong in data + AI workloads; underpins Thought Machine.",
    suggestedTier: "TIER_1",
    isDoraCritical: true,
    hyperscaler: "GCP",
    region: "europe-west2",
    assuranceKind: "SOC2_TYPE_2",
    statusUrl: "https://status.cloud.google.com",
  },
  {
    slug: "cloudflare",
    name: "Cloudflare",
    serviceKind: "Edge / CDN / DDoS protection",
    category: "Cloud & infra",
    sectors: ["banking", "insurance", "asset-wealth", "payments-fintech", "telecoms", "energy-utilities", "retail-ecommerce", "healthcare", "government", "aviation-transport", "logistics", "media-broadcasting", "higher-ed", "manufacturing", "technology-saas", "legal-professional"],
    description: "Edge network + WAF + DDoS protection in front of customer-facing services.",
    suggestedTier: "TIER_2",
    isDoraCritical: true,
    statusUrl: "https://www.cloudflarestatus.com",
  },
  {
    slug: "datadog",
    name: "Datadog",
    serviceKind: "Observability (metrics / logs / APM)",
    category: "Cloud & infra",
    sectors: ["banking", "insurance", "asset-wealth", "payments-fintech", "telecoms", "energy-utilities", "retail-ecommerce", "healthcare", "government", "aviation-transport", "logistics", "media-broadcasting", "higher-ed", "manufacturing", "technology-saas", "legal-professional"],
    description: "Observability platform — metrics, logs, traces, RUM.",
    suggestedTier: "TIER_2",
    isDoraCritical: false,
    statusUrl: "https://status.datadoghq.com",
  },

  // ─── Communications ───────────────────────────────────────────────────
  {
    slug: "twilio",
    name: "Twilio",
    serviceKind: "SMS / voice / OTP",
    category: "Communications",
    sectors: ["banking", "insurance", "payments-fintech", "telecoms", "retail-ecommerce", "healthcare", "government", "technology-saas"],
    description: "Communications API — SMS, OTP, voice, WhatsApp Business.",
    suggestedTier: "TIER_2",
    isDoraCritical: false,
    statusUrl: "https://status.twilio.com",
  },
  {
    slug: "sendgrid",
    name: "SendGrid (Twilio)",
    serviceKind: "Transactional + marketing email",
    category: "Communications",
    sectors: ["banking", "insurance", "payments-fintech", "telecoms", "retail-ecommerce", "healthcare", "government", "technology-saas"],
    description: "Transactional email at scale; part of Twilio.",
    suggestedTier: "TIER_2",
    isDoraCritical: false,
  },
  {
    slug: "auth0",
    name: "Auth0 (Okta)",
    serviceKind: "Identity-as-a-service (IdP)",
    category: "Communications",
    sectors: ["banking", "insurance", "payments-fintech", "telecoms", "retail-ecommerce", "healthcare", "government", "technology-saas"],
    description: "Customer + workforce IdP. Often the auth backbone for fintech apps.",
    suggestedTier: "TIER_1",
    isDoraCritical: true,
    statusUrl: "https://status.auth0.com",
  },

  // ─── Customer & CRM ───────────────────────────────────────────────────
  {
    slug: "salesforce",
    name: "Salesforce",
    serviceKind: "CRM / customer data",
    category: "Customer & CRM",
    sectors: ["banking", "insurance", "retail-ecommerce", "telecoms", "asset-wealth", "technology-saas"],
    description: "Enterprise CRM — common in branch / commercial banking.",
    suggestedTier: "TIER_2",
    isDoraCritical: false,
  },
  {
    slug: "zendesk",
    name: "Zendesk",
    serviceKind: "Customer support + ticketing",
    category: "Customer & CRM",
    sectors: ["banking", "insurance", "retail-ecommerce", "telecoms", "asset-wealth", "technology-saas"],
    description: "Multi-channel customer support platform — voice, email, chat, social.",
    suggestedTier: "TIER_3",
    isDoraCritical: false,
  },
  {
    slug: "intercom",
    name: "Intercom",
    serviceKind: "In-app messaging + support",
    category: "Customer & CRM",
    sectors: ["banking", "insurance", "retail-ecommerce", "telecoms", "asset-wealth", "technology-saas"],
    description: "Conversational support + in-app messaging — common in fintech apps.",
    suggestedTier: "TIER_3",
    isDoraCritical: false,
  },

  // ─── Treasury ─────────────────────────────────────────────────────────
  {
    slug: "kyriba",
    name: "Kyriba",
    serviceKind: "Treasury management",
    category: "Treasury",
    sectors: ["banking", "asset-wealth"],
    description: "Cloud-based treasury, risk and payments suite.",
    suggestedTier: "TIER_2",
    isDoraCritical: false,
  },
  {
    slug: "ion-treasury",
    name: "ION Treasury",
    serviceKind: "Treasury & risk management",
    category: "Treasury",
    sectors: ["banking", "asset-wealth"],
    description: "Enterprise treasury technology used by large banks.",
    suggestedTier: "TIER_2",
    isDoraCritical: false,
  },

  // ─── Energy & utilities ───────────────────────────────────────────────
  {
    slug: "siemens-spectrum",
    name: "Siemens Spectrum Power",
    serviceKind: "Energy-management system (EMS) / SCADA",
    category: "Energy & utilities",
    sectors: ["energy-utilities"],
    description: "Grid-control EMS / SCADA used by transmission and distribution operators.",
    suggestedTier: "TIER_1",
    isDoraCritical: false,
  },
  {
    slug: "ge-grid-solutions",
    name: "GE Grid Solutions",
    serviceKind: "Grid automation, protection and control",
    category: "Energy & utilities",
    sectors: ["energy-utilities"],
    description: "Substation automation, protection relays and grid-monitoring software.",
    suggestedTier: "TIER_1",
    isDoraCritical: false,
  },
  {
    slug: "schneider-electric",
    name: "Schneider Electric",
    serviceKind: "Industrial automation & energy management",
    category: "Energy & utilities",
    sectors: ["energy-utilities", "manufacturing"],
    description: "OT / SCADA platform Modicon, EcoStruxure — power, grid and industrial automation.",
    suggestedTier: "TIER_1",
    isDoraCritical: false,
  },
  {
    slug: "trayport",
    name: "Trayport",
    serviceKind: "Energy & commodities trading platform",
    category: "Energy & utilities",
    sectors: ["energy-utilities"],
    description: "Cross-broker price discovery and trade-execution platform for European energy markets.",
    suggestedTier: "TIER_2",
    isDoraCritical: false,
  },
  {
    slug: "kraken-technologies",
    name: "Kraken (Octopus Energy)",
    serviceKind: "Energy-retail platform",
    category: "Energy & utilities",
    sectors: ["energy-utilities"],
    description: "Customer-platform for energy retail — billing, customer service, smart-meter data.",
    suggestedTier: "TIER_2",
    isDoraCritical: false,
  },
  {
    slug: "smart-dcc",
    name: "Smart DCC",
    serviceKind: "Smart-meter communications network",
    category: "Energy & utilities",
    sectors: ["energy-utilities"],
    description: "Licensed national smart-meter communications infrastructure.",
    suggestedTier: "TIER_1",
    isDoraCritical: false,
  },

  // ─── Telecoms infra ────────────────────────────────────────────────────
  {
    slug: "openreach",
    name: "Openreach (BT)",
    serviceKind: "Wholesale fixed-line access network",
    category: "Telecoms infra",
    sectors: ["telecoms"],
    description: "UK national fixed-line access network — fibre, copper, leased lines.",
    suggestedTier: "TIER_1",
    isDoraCritical: false,
  },
  {
    slug: "ericsson",
    name: "Ericsson",
    serviceKind: "Mobile core & RAN equipment",
    category: "Telecoms infra",
    sectors: ["telecoms"],
    description: "Mobile core (HSS / UDM / PGW) and RAN equipment supplier to UK MNOs.",
    suggestedTier: "TIER_1",
    isDoraCritical: false,
  },
  {
    slug: "nokia-telecoms",
    name: "Nokia",
    serviceKind: "Mobile core & transport equipment",
    category: "Telecoms infra",
    sectors: ["telecoms"],
    description: "Mobile network and IP / optical-transport equipment vendor.",
    suggestedTier: "TIER_1",
    isDoraCritical: false,
  },
  {
    slug: "amdocs",
    name: "Amdocs",
    serviceKind: "Telco BSS / OSS",
    category: "Telecoms infra",
    sectors: ["telecoms"],
    description: "Billing-and-customer-management suite used by major MNOs.",
    suggestedTier: "TIER_1",
    isDoraCritical: false,
  },
  {
    slug: "csl-bsi",
    name: "CSL (BT)",
    serviceKind: "Connectivity for alarm & telecare",
    category: "Telecoms infra",
    sectors: ["telecoms"],
    description: "M2M and alarm-network connectivity provider — relied on for telecare and security alarms.",
    suggestedTier: "TIER_2",
    isDoraCritical: false,
  },

  // ─── Healthcare IT ─────────────────────────────────────────────────────
  {
    slug: "epic-healthcare",
    name: "Epic",
    serviceKind: "Electronic patient record",
    category: "Healthcare IT",
    sectors: ["healthcare"],
    description: "Hospital EPR widely used by NHS Foundation Trusts (Cambridge, GOSH and others).",
    suggestedTier: "TIER_1",
    isDoraCritical: false,
  },
  {
    slug: "cerner-oracle-health",
    name: "Oracle Health (Cerner)",
    serviceKind: "Electronic patient record",
    category: "Healthcare IT",
    sectors: ["healthcare"],
    description: "Hospital EPR platform, large global footprint including UK trusts.",
    suggestedTier: "TIER_1",
    isDoraCritical: false,
  },
  {
    slug: "emis-health",
    name: "EMIS Health",
    serviceKind: "Primary-care clinical system",
    category: "Healthcare IT",
    sectors: ["healthcare"],
    description: "GP-practice clinical system, used by ~50% of UK GP practices.",
    suggestedTier: "TIER_1",
    isDoraCritical: false,
  },
  {
    slug: "tpp-systmone",
    name: "TPP SystmOne",
    serviceKind: "Primary & secondary-care clinical system",
    category: "Healthcare IT",
    sectors: ["healthcare"],
    description: "Clinical system used across UK GP practices, community and acute trusts.",
    suggestedTier: "TIER_1",
    isDoraCritical: false,
  },
  {
    slug: "synnovis",
    name: "Synnovis",
    serviceKind: "Pathology services",
    category: "Healthcare IT",
    sectors: ["healthcare"],
    description: "Pathology service provider to multiple NHS trusts (King's, Guy's & St Thomas').",
    suggestedTier: "TIER_1",
    isDoraCritical: false,
  },
  {
    slug: "philips-healthcare",
    name: "Philips Healthcare",
    serviceKind: "Medical imaging & patient monitoring",
    category: "Healthcare IT",
    sectors: ["healthcare"],
    description: "Imaging (CT, MRI), bedside monitoring and IntelliVue patient-monitoring systems.",
    suggestedTier: "TIER_1",
    isDoraCritical: false,
  },
  {
    slug: "ge-healthcare",
    name: "GE HealthCare",
    serviceKind: "Imaging & monitoring equipment",
    category: "Healthcare IT",
    sectors: ["healthcare"],
    description: "Imaging modalities and patient-monitoring equipment.",
    suggestedTier: "TIER_1",
    isDoraCritical: false,
  },
  {
    slug: "nhs-mail",
    name: "NHS Mail",
    serviceKind: "Secure mail platform (Microsoft 365)",
    category: "Healthcare IT",
    sectors: ["healthcare"],
    description: "Centralised secure email and collaboration service used across NHS organisations.",
    suggestedTier: "TIER_1",
    isDoraCritical: false,
  },

  // ─── Retail & ecommerce ────────────────────────────────────────────────
  {
    slug: "shopify",
    name: "Shopify",
    serviceKind: "E-commerce platform",
    category: "Retail & ecommerce",
    sectors: ["retail-ecommerce"],
    description: "Hosted e-commerce platform — checkout, storefront, payments.",
    suggestedTier: "TIER_1",
    isDoraCritical: false,
    statusUrl: "https://www.shopifystatus.com",
  },
  {
    slug: "adyen",
    name: "Adyen",
    serviceKind: "Payments processor & acquirer",
    category: "Retail & ecommerce",
    sectors: ["retail-ecommerce", "payments-fintech"],
    description: "Unified payments processor — card, alt-payments, in-store and online.",
    suggestedTier: "TIER_1",
    isDoraCritical: true,
    statusUrl: "https://status.adyen.com",
  },
  {
    slug: "klarna",
    name: "Klarna",
    serviceKind: "Buy-now-pay-later",
    category: "Retail & ecommerce",
    sectors: ["retail-ecommerce", "payments-fintech"],
    description: "BNPL provider — checkout integration with millions of merchants.",
    suggestedTier: "TIER_2",
    isDoraCritical: false,
  },
  {
    slug: "ngc-software",
    name: "Manhattan Associates",
    serviceKind: "Warehouse-management system (WMS)",
    category: "Retail & ecommerce",
    sectors: ["retail-ecommerce", "logistics"],
    description: "Enterprise WMS used by large retail and 3PL operations.",
    suggestedTier: "TIER_1",
    isDoraCritical: false,
  },
  {
    slug: "criteo",
    name: "Criteo",
    serviceKind: "Performance advertising / retargeting",
    category: "Retail & ecommerce",
    sectors: ["retail-ecommerce", "media-broadcasting"],
    description: "Retargeting advertising platform.",
    suggestedTier: "TIER_3",
    isDoraCritical: false,
  },

  // ─── Transport & travel ────────────────────────────────────────────────
  {
    slug: "amadeus-travel",
    name: "Amadeus",
    serviceKind: "Airline reservation & GDS",
    category: "Transport & travel",
    sectors: ["aviation-transport"],
    description: "Global distribution system + airline passenger-service platform.",
    suggestedTier: "TIER_1",
    isDoraCritical: false,
  },
  {
    slug: "sabre",
    name: "Sabre",
    serviceKind: "Airline reservation & GDS",
    category: "Transport & travel",
    sectors: ["aviation-transport"],
    description: "Airline reservation platform and GDS — used by many global airlines.",
    suggestedTier: "TIER_1",
    isDoraCritical: false,
  },
  {
    slug: "iata-bsp",
    name: "IATA BSP",
    serviceKind: "Airline ticket settlement",
    category: "Transport & travel",
    sectors: ["aviation-transport"],
    description: "Billing and Settlement Plan — global airline ticket settlement infrastructure.",
    suggestedTier: "TIER_1",
    isDoraCritical: false,
  },
  {
    slug: "nats",
    name: "NATS",
    serviceKind: "UK air traffic services",
    category: "Transport & travel",
    sectors: ["aviation-transport"],
    description: "Air-navigation service provider for UK airspace.",
    suggestedTier: "TIER_1",
    isDoraCritical: false,
  },

  // ─── Logistics & shipping ──────────────────────────────────────────────
  {
    slug: "dhl",
    name: "DHL",
    serviceKind: "International express & freight",
    category: "Logistics & shipping",
    sectors: ["logistics", "retail-ecommerce"],
    description: "Global parcel and freight carrier.",
    suggestedTier: "TIER_1",
    isDoraCritical: false,
  },
  {
    slug: "dpd",
    name: "DPD",
    serviceKind: "Last-mile parcel delivery",
    category: "Logistics & shipping",
    sectors: ["logistics", "retail-ecommerce"],
    description: "UK and European last-mile parcel network.",
    suggestedTier: "TIER_2",
    isDoraCritical: false,
  },
  {
    slug: "evri-hermes",
    name: "Evri (formerly Hermes)",
    serviceKind: "Last-mile parcel delivery",
    category: "Logistics & shipping",
    sectors: ["logistics", "retail-ecommerce"],
    description: "UK final-mile delivery network.",
    suggestedTier: "TIER_2",
    isDoraCritical: false,
  },
  {
    slug: "royal-mail",
    name: "Royal Mail",
    serviceKind: "Postal & parcels carrier",
    category: "Logistics & shipping",
    sectors: ["logistics", "retail-ecommerce"],
    description: "UK universal-service postal operator + parcels (Parcelforce).",
    suggestedTier: "TIER_1",
    isDoraCritical: false,
  },
  {
    slug: "maersk",
    name: "Maersk",
    serviceKind: "Container shipping",
    category: "Logistics & shipping",
    sectors: ["logistics", "manufacturing"],
    description: "Global container shipping line and integrated-logistics provider.",
    suggestedTier: "TIER_1",
    isDoraCritical: false,
  },

  // ─── Government IT ─────────────────────────────────────────────────────
  {
    slug: "capita",
    name: "Capita",
    serviceKind: "Public-sector outsourced services",
    category: "Government IT",
    sectors: ["government"],
    description: "Outsourced services — utilities customer service, DVLA, MoD.",
    suggestedTier: "TIER_1",
    isDoraCritical: false,
  },
  {
    slug: "atos-uk",
    name: "Atos",
    serviceKind: "IT services to government",
    category: "Government IT",
    sectors: ["government"],
    description: "Long-tenured government IT supplier (DWP, NHS, Home Office).",
    suggestedTier: "TIER_1",
    isDoraCritical: false,
  },
  {
    slug: "fujitsu-uk",
    name: "Fujitsu UK",
    serviceKind: "IT services to government",
    category: "Government IT",
    sectors: ["government"],
    description: "Major UK government IT outsourcer.",
    suggestedTier: "TIER_1",
    isDoraCritical: false,
  },
  {
    slug: "gov-uk-notify",
    name: "GOV.UK Notify",
    serviceKind: "Government messaging (email / SMS)",
    category: "Government IT",
    sectors: ["government"],
    description: "Cross-government notifications platform (GDS).",
    suggestedTier: "TIER_2",
    isDoraCritical: false,
  },

  // ─── Education tech ────────────────────────────────────────────────────
  {
    slug: "blackboard",
    name: "Blackboard / Anthology",
    serviceKind: "Virtual learning environment",
    category: "Education tech",
    sectors: ["higher-ed"],
    description: "VLE used by universities and FE colleges.",
    suggestedTier: "TIER_1",
    isDoraCritical: false,
  },
  {
    slug: "canvas-lms",
    name: "Canvas LMS (Instructure)",
    serviceKind: "Virtual learning environment",
    category: "Education tech",
    sectors: ["higher-ed"],
    description: "Cloud LMS for universities, schools and corporate training.",
    suggestedTier: "TIER_1",
    isDoraCritical: false,
  },
  {
    slug: "moodle",
    name: "Moodle",
    serviceKind: "Open-source VLE",
    category: "Education tech",
    sectors: ["higher-ed"],
    description: "Open-source VLE often hosted by partner like Moodle Workplace / Catalyst.",
    suggestedTier: "TIER_2",
    isDoraCritical: false,
  },
  {
    slug: "turnitin",
    name: "Turnitin",
    serviceKind: "Plagiarism detection",
    category: "Education tech",
    sectors: ["higher-ed"],
    description: "Originality-checking for student-submitted work.",
    suggestedTier: "TIER_2",
    isDoraCritical: false,
  },

  // ─── Media & broadcast ─────────────────────────────────────────────────
  {
    slug: "akamai",
    name: "Akamai",
    serviceKind: "CDN & media delivery",
    category: "Media & broadcast",
    sectors: ["media-broadcasting", "technology-saas"],
    description: "Content delivery network — heavily used by broadcasters and streamers.",
    suggestedTier: "TIER_1",
    isDoraCritical: false,
  },
  {
    slug: "amazon-mediastore",
    name: "AWS MediaLive / MediaPackage",
    serviceKind: "Live video streaming infrastructure",
    category: "Media & broadcast",
    sectors: ["media-broadcasting"],
    description: "AWS-managed live broadcast and streaming services.",
    suggestedTier: "TIER_2",
    isDoraCritical: false,
  },
  {
    slug: "avid",
    name: "Avid Technology",
    serviceKind: "Production & editing tools",
    category: "Media & broadcast",
    sectors: ["media-broadcasting"],
    description: "Editing and media-asset-management platforms used in TV / film post-production.",
    suggestedTier: "TIER_2",
    isDoraCritical: false,
  },
  {
    slug: "redbee",
    name: "Red Bee Media",
    serviceKind: "Broadcast playout & managed services",
    category: "Media & broadcast",
    sectors: ["media-broadcasting"],
    description: "Managed playout and OTT services for broadcasters.",
    suggestedTier: "TIER_1",
    isDoraCritical: false,
  },

  // ─── Manufacturing & industrial ────────────────────────────────────────
  {
    slug: "sap-erp",
    name: "SAP S/4HANA",
    serviceKind: "Enterprise resource planning",
    category: "Manufacturing & industrial",
    sectors: ["manufacturing", "retail-ecommerce", "energy-utilities", "logistics"],
    description: "Tier-1 ERP backbone — finance, supply-chain, manufacturing.",
    suggestedTier: "TIER_1",
    isDoraCritical: false,
  },
  {
    slug: "oracle-erp",
    name: "Oracle ERP Cloud",
    serviceKind: "Enterprise resource planning",
    category: "Manufacturing & industrial",
    sectors: ["manufacturing", "retail-ecommerce", "asset-wealth"],
    description: "ERP suite — finance, procurement, project management.",
    suggestedTier: "TIER_1",
    isDoraCritical: false,
  },
  {
    slug: "rockwell-automation",
    name: "Rockwell Automation",
    serviceKind: "Industrial automation & control",
    category: "Manufacturing & industrial",
    sectors: ["manufacturing"],
    description: "PLC / SCADA hardware and software — Allen-Bradley, FactoryTalk.",
    suggestedTier: "TIER_1",
    isDoraCritical: false,
  },
  {
    slug: "honeywell-process",
    name: "Honeywell Process Solutions",
    serviceKind: "Process-control systems",
    category: "Manufacturing & industrial",
    sectors: ["manufacturing", "energy-utilities"],
    description: "DCS and process-control platforms (Experion).",
    suggestedTier: "TIER_1",
    isDoraCritical: false,
  },

  // ─── Cybersecurity ─────────────────────────────────────────────────────
  {
    slug: "crowdstrike",
    name: "CrowdStrike",
    serviceKind: "EDR / endpoint security",
    category: "Cybersecurity",
    sectors: ["banking", "insurance", "asset-wealth", "payments-fintech", "telecoms", "energy-utilities", "retail-ecommerce", "healthcare", "government", "aviation-transport", "logistics", "media-broadcasting", "higher-ed", "manufacturing", "technology-saas", "legal-professional"],
    description: "Cloud-delivered EDR / XDR — Falcon platform.",
    suggestedTier: "TIER_1",
    isDoraCritical: true,
    assuranceKind: "SOC2_TYPE_2",
    statusUrl: "https://status.crowdstrike.com",
  },
  {
    slug: "sentinelone",
    name: "SentinelOne",
    serviceKind: "EDR / endpoint security",
    category: "Cybersecurity",
    sectors: ["banking", "insurance", "asset-wealth", "payments-fintech", "telecoms", "energy-utilities", "retail-ecommerce", "healthcare", "government", "aviation-transport", "logistics", "media-broadcasting", "higher-ed", "manufacturing", "technology-saas", "legal-professional"],
    description: "Autonomous endpoint protection platform.",
    suggestedTier: "TIER_2",
    isDoraCritical: false,
  },
  {
    slug: "palo-alto-networks",
    name: "Palo Alto Networks",
    serviceKind: "Network security & SASE",
    category: "Cybersecurity",
    sectors: ["banking", "insurance", "asset-wealth", "payments-fintech", "telecoms", "energy-utilities", "retail-ecommerce", "healthcare", "government", "aviation-transport", "logistics", "media-broadcasting", "higher-ed", "manufacturing", "technology-saas", "legal-professional"],
    description: "Next-gen firewalls and Prisma Access SASE platform.",
    suggestedTier: "TIER_1",
    isDoraCritical: false,
  },
  {
    slug: "splunk",
    name: "Splunk",
    serviceKind: "SIEM / log analytics",
    category: "Cybersecurity",
    sectors: ["banking", "insurance", "asset-wealth", "payments-fintech", "telecoms", "energy-utilities", "retail-ecommerce", "healthcare", "government", "aviation-transport", "logistics", "media-broadcasting", "higher-ed", "manufacturing", "technology-saas", "legal-professional"],
    description: "Log analytics and SIEM platform.",
    suggestedTier: "TIER_1",
    isDoraCritical: false,
  },
  {
    slug: "okta",
    name: "Okta",
    serviceKind: "Workforce identity (IdP)",
    category: "Cybersecurity",
    sectors: ["banking", "insurance", "asset-wealth", "payments-fintech", "telecoms", "energy-utilities", "retail-ecommerce", "healthcare", "government", "aviation-transport", "logistics", "media-broadcasting", "higher-ed", "manufacturing", "technology-saas", "legal-professional"],
    description: "Workforce identity-provider, SSO and conditional access.",
    suggestedTier: "TIER_1",
    isDoraCritical: true,
    statusUrl: "https://status.okta.com",
  },
  {
    slug: "microsoft-entra",
    name: "Microsoft Entra ID",
    serviceKind: "Workforce identity (Azure AD)",
    category: "Cybersecurity",
    sectors: ["banking", "insurance", "asset-wealth", "payments-fintech", "telecoms", "energy-utilities", "retail-ecommerce", "healthcare", "government", "aviation-transport", "logistics", "media-broadcasting", "higher-ed", "manufacturing", "technology-saas", "legal-professional"],
    description: "Microsoft cloud identity — SSO, MFA, conditional access.",
    suggestedTier: "TIER_1",
    isDoraCritical: true,
  },
  {
    slug: "1password-business",
    name: "1Password Business",
    serviceKind: "Password & secret management",
    category: "Cybersecurity",
    sectors: ["banking", "insurance", "asset-wealth", "payments-fintech", "telecoms", "energy-utilities", "retail-ecommerce", "healthcare", "government", "aviation-transport", "logistics", "media-broadcasting", "higher-ed", "manufacturing", "technology-saas", "legal-professional"],
    description: "Enterprise password manager and secrets sharing.",
    suggestedTier: "TIER_3",
    isDoraCritical: false,
  },

  // ─── Productivity & HR ─────────────────────────────────────────────────
  {
    slug: "microsoft-365",
    name: "Microsoft 365",
    serviceKind: "Productivity & collaboration",
    category: "Productivity & HR",
    sectors: ["banking", "insurance", "asset-wealth", "payments-fintech", "telecoms", "energy-utilities", "retail-ecommerce", "healthcare", "government", "aviation-transport", "logistics", "media-broadcasting", "higher-ed", "manufacturing", "technology-saas", "legal-professional"],
    description: "Email, Office, Teams, SharePoint, OneDrive across the workforce.",
    suggestedTier: "TIER_1",
    isDoraCritical: true,
    statusUrl: "https://status.office365.com",
  },
  {
    slug: "google-workspace",
    name: "Google Workspace",
    serviceKind: "Productivity & collaboration",
    category: "Productivity & HR",
    sectors: ["banking", "insurance", "asset-wealth", "payments-fintech", "telecoms", "energy-utilities", "retail-ecommerce", "healthcare", "government", "aviation-transport", "logistics", "media-broadcasting", "higher-ed", "manufacturing", "technology-saas", "legal-professional"],
    description: "Gmail, Docs, Drive, Meet, Calendar across the workforce.",
    suggestedTier: "TIER_1",
    isDoraCritical: true,
  },
  {
    slug: "slack",
    name: "Slack",
    serviceKind: "Workplace messaging",
    category: "Productivity & HR",
    sectors: ["banking", "insurance", "asset-wealth", "payments-fintech", "telecoms", "energy-utilities", "retail-ecommerce", "healthcare", "government", "aviation-transport", "logistics", "media-broadcasting", "higher-ed", "manufacturing", "technology-saas", "legal-professional"],
    description: "Workplace chat and channels — often the de-facto incident-bridge.",
    suggestedTier: "TIER_2",
    isDoraCritical: false,
  },
  {
    slug: "workday",
    name: "Workday",
    serviceKind: "HR & finance",
    category: "Productivity & HR",
    sectors: ["banking", "insurance", "asset-wealth", "payments-fintech", "telecoms", "energy-utilities", "retail-ecommerce", "healthcare", "government", "aviation-transport", "logistics", "media-broadcasting", "higher-ed", "manufacturing", "technology-saas", "legal-professional"],
    description: "HCM and finance cloud — workforce, payroll, learning, finance.",
    suggestedTier: "TIER_1",
    isDoraCritical: false,
  },
  {
    slug: "servicenow",
    name: "ServiceNow",
    serviceKind: "IT service management & workflow",
    category: "Productivity & HR",
    sectors: ["banking", "insurance", "asset-wealth", "payments-fintech", "telecoms", "energy-utilities", "retail-ecommerce", "healthcare", "government", "aviation-transport", "logistics", "media-broadcasting", "higher-ed", "manufacturing", "technology-saas", "legal-professional"],
    description: "Enterprise workflow platform — ITSM, HRSD, GRC.",
    suggestedTier: "TIER_1",
    isDoraCritical: false,
  },
  {
    slug: "pagerduty",
    name: "PagerDuty",
    serviceKind: "Incident response & on-call",
    category: "Productivity & HR",
    sectors: ["banking", "insurance", "asset-wealth", "payments-fintech", "telecoms", "energy-utilities", "retail-ecommerce", "healthcare", "government", "aviation-transport", "logistics", "media-broadcasting", "higher-ed", "manufacturing", "technology-saas", "legal-professional"],
    description: "On-call alerting and incident response platform.",
    suggestedTier: "TIER_2",
    isDoraCritical: false,
  },
];

export function vendorBySlug(slug: string): LibraryVendor | null {
  return VENDOR_LIBRARY.find((v) => v.slug === slug) ?? null;
}
