import { redirect } from "next/navigation";
import { auth } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { loadMaturitySummary } from "@/lib/achievements/summary";
import MaturityStrip from "@/components/achievements/MaturityStrip";
import StatementPrintButton from "@/components/achievements/StatementPrintButton";
import {
  LEVEL_LABEL,
  LEVEL_DESCRIPTION,
  type AchievementLevel,
  type AchievementTopic,
} from "@/lib/achievements/types";

export const metadata = { title: "Maturity statement — SnapFix" };

const LEVELS: AchievementLevel[] = [1, 2, 3, 4, 5];

/**
 * One-page maturity statement designed to land in the Board pack as a PDF.
 * Renders the per-topic ladder with progress bars + a verbal level statement
 * a CRO can read aloud. Print stylesheet does the work — `window.print()`
 * outputs cleanly without a separate PDF generator.
 */
export default async function MaturityStatementPage() {
  const session = await auth();
  if (!session?.user?.orgId) redirect("/sign-in");

  const [org, summary] = await Promise.all([
    prisma.organization.findUnique({
      where: { id: session.user.orgId },
      select: { name: true },
    }),
    loadMaturitySummary(session.user.orgId),
  ]);

  const now = new Date();
  const generatedAt = now.toISOString().slice(0, 10);

  return (
    <div className="space-y-6 print:space-y-3">
      <div className="flex flex-wrap items-center justify-between gap-3 print:hidden">
        <div>
          <h1 className="font-display text-2xl font-semibold tracking-tight text-ink">
            Maturity statement
          </h1>
          <p className="text-sm text-muted">
            Print-friendly one-pager for the Board pack — uses{" "}
            <code className="rounded bg-surface-2 px-1 py-0.5 text-[11px]">
              window.print()
            </code>{" "}
            so the export is the same content you see here.
          </p>
        </div>
        <StatementPrintButton />
      </div>

      <article className="rounded-2xl border border-line bg-surface-1 p-6 print:rounded-none print:border-0 print:bg-transparent print:p-0">
        <header className="border-b border-line pb-3">
          <p className="text-[10px] font-semibold uppercase tracking-[0.18em] text-soft">
            {org?.name ?? "—"} · Operational resilience
          </p>
          <h2 className="mt-1 font-display text-2xl font-semibold text-ink">
            Resilience maturity statement
          </h2>
          <p className="mt-1 text-[11px] text-soft">
            As of {generatedAt} · {summary.totalUnlocked} of {summary.totalRules}{" "}
            achievements unlocked · {summary.totalXp.toLocaleString()} XP
          </p>
        </header>

        <div className="mt-5">
          <MaturityStrip
            maturity={summary.maturity}
            title="Per-topic ladder"
            pitch="Each topic carries 5 maturity levels (Awareness → Optimised). The pill colour shows how many rules in that level are unlocked."
          />
        </div>

        <section className="mt-6 grid gap-5 print:break-before-auto sm:grid-cols-2">
          {summary.maturity.map((m) => (
            <TopicNarrative key={m.topic} topic={m.topic} m={m} />
          ))}
        </section>

        <footer className="mt-6 border-t border-line pt-3 text-[10px] text-soft print:break-inside-avoid">
          <p>
            Maturity model: L1 Awareness · L2 Documented · L3 Tested · L4 Measured ·
            L5 Optimised. A topic reaches a level when ≥70% of its rules at that
            level are unlocked.
          </p>
          <p className="mt-1">
            Generated by SnapFix · {generatedAt} · powered by the Achievements engine
            (250 rules across 5 topics).
          </p>
        </footer>
      </article>
    </div>
  );
}

function TopicNarrative({
  topic,
  m,
}: {
  topic: AchievementTopic;
  m: {
    topic: AchievementTopic;
    topicLabel: string;
    unlockedByLevel: Record<AchievementLevel, number>;
    totalByLevel: Record<AchievementLevel, number>;
    level: 0 | AchievementLevel;
    progressInLevel: number;
  };
}) {
  void topic;
  const narrative = buildNarrative(m);
  return (
    <article className="rounded-xl border border-line bg-surface-0 p-4 print:break-inside-avoid">
      <header>
        <p className="text-[10px] font-semibold uppercase tracking-wider text-soft">
          {m.topicLabel}
        </p>
        <p className="mt-1 font-display text-xl font-bold text-ink">
          L{m.level || 0}
          <span className="ml-2 text-sm font-medium text-muted">
            {m.level === 0 ? "Awakening" : LEVEL_LABEL[m.level as AchievementLevel]}
          </span>
        </p>
      </header>

      <p className="mt-2 text-[12px] text-soft">{narrative}</p>

      <ul className="mt-3 space-y-1.5 text-[11px]">
        {LEVELS.map((l) => {
          const filled = m.unlockedByLevel[l] === m.totalByLevel[l] && m.totalByLevel[l] > 0;
          const pct =
            m.totalByLevel[l] === 0
              ? 0
              : Math.round((m.unlockedByLevel[l] / m.totalByLevel[l]) * 100);
          return (
            <li key={l} className="flex items-center gap-2">
              <span
                className={`inline-flex h-5 w-9 flex-none items-center justify-center rounded text-[9px] font-bold uppercase tracking-wider ${
                  filled
                    ? "bg-emerald-500 text-white dark:bg-emerald-600"
                    : "bg-surface-2 text-soft"
                }`}
              >
                L{l}
              </span>
              <span className="flex-1 text-[11px] text-ink">{LEVEL_LABEL[l]}</span>
              <span className="font-mono text-[10px] text-soft">
                {m.unlockedByLevel[l]}/{m.totalByLevel[l]} · {pct}%
              </span>
            </li>
          );
        })}
      </ul>
    </article>
  );
}

function buildNarrative(m: {
  level: 0 | AchievementLevel;
  topicLabel: string;
  progressInLevel: number;
}): string {
  if (m.level === 0) {
    return `${m.topicLabel} is at the awakening stage — the inventory hasn't been captured yet. Start with L1 Awareness to put the spine of the programme in place.`;
  }
  const desc = LEVEL_DESCRIPTION[m.level as AchievementLevel];
  if (m.level === 5) {
    return `${m.topicLabel} is at L5 Optimised. ${desc} Sustain the score quarter on quarter.`;
  }
  const nextLevel = (m.level + 1) as AchievementLevel;
  const pct = Math.round(m.progressInLevel * 100);
  return `${m.topicLabel} is at L${m.level} ${LEVEL_LABEL[m.level as AchievementLevel]}. ${desc} ${pct}% of the way into L${nextLevel} ${LEVEL_LABEL[nextLevel]}.`;
}
