import { AlertTriangle, Clock, MessageSquareWarning } from "lucide-react";
import SitrepDrawer from "./SitrepDrawer";

type Sitrep = {
  id: string;
  businessUnit: string;
  status: "GREEN" | "AMBER" | "RED";
  nextUpdateDDayTime: string | null;
  dDayTime: string;
  createdAt: Date;
};

type Props = {
  sitreps: Sitrep[];
  /** Current D-Day clock as "HH:MM". */
  dDayHHMM: string;
  /** Wall-clock minutes since the most-recent sitrep was filed. */
  minutesSinceLastSitrep: number | null;
  /** Has an incident been invoked? Hide the banner entirely if not. */
  incidentActive: boolean;
  /** Exercise + incident ids passed to the sitrep drawer button. Null
   *  when there's no incident; banner is hidden then anyway. */
  exerciseId: string;
  incidentId: string | null;
};

/**
 * Surfaces sitrep-cadence breaches. Doctrine expects an initial sitrep
 * from each affected business unit within 15 minutes of invocation,
 * then updates on the cadence each sitrep declared (nextUpdateDDayTime).
 * When that promise slips, the war-room is flying blind — so we say so
 * out loud.
 *
 * Three escalating states:
 *  - QUIET: no incident, or sitreps within cadence → renders nothing
 *  - INFO:  no sitreps yet → "First sitrep due from each BU"
 *  - WARN:  one or more sitreps overdue → list them with delta
 */
export default function SitrepCadenceBanner({
  sitreps,
  dDayHHMM,
  minutesSinceLastSitrep,
  incidentActive,
  exerciseId,
  incidentId,
}: Props) {
  if (!incidentActive || !incidentId) return null;

  const dDayMins = ddayToMinutes(dDayHHMM);

  if (sitreps.length === 0) {
    return (
      <div className="flex items-start gap-3 rounded-md border border-amber-200 bg-amber-50 p-3 text-xs dark:border-amber-800/60 dark:bg-amber-950/30">
        <MessageSquareWarning size={14} className="mt-0.5 shrink-0 text-amber-700 dark:text-amber-300" />
        <div className="min-w-0 flex-1">
          <p className="font-semibold text-amber-900 dark:text-amber-100">
            No sitreps filed yet
          </p>
          <p className="mt-0.5 text-amber-800 dark:text-amber-200">
            Each affected business unit should file an initial sitrep within 15 min of
            incident invocation.
          </p>
        </div>
        <SitrepDrawer
          exerciseId={exerciseId}
          incidentId={incidentId}
          dDayHHMM={dDayHHMM}
        />
      </div>
    );
  }

  // Find sitreps whose promised next-update D-Day time is in the past.
  // We compare HH:MM lexicographically only if both are in HH:MM form —
  // dDayHHMM is generated by the same currentDDay helper so that holds.
  const latestPerBU = new Map<string, Sitrep>();
  for (const s of sitreps) {
    const prior = latestPerBU.get(s.businessUnit);
    if (!prior || s.createdAt > prior.createdAt) latestPerBU.set(s.businessUnit, s);
  }

  const overdue = [...latestPerBU.values()]
    .filter((s) => {
      if (!s.nextUpdateDDayTime) return false;
      const promised = ddayToMinutes(s.nextUpdateDDayTime);
      return promised !== null && dDayMins !== null && promised < dDayMins;
    })
    .map((s) => {
      const promised = ddayToMinutes(s.nextUpdateDDayTime!)!;
      const dueAgo = dDayMins! - promised;
      return { ...s, dueAgo };
    })
    .sort((a, b) => b.dueAgo - a.dueAgo);

  const staleSinceLast =
    minutesSinceLastSitrep !== null && minutesSinceLastSitrep > 60;

  if (overdue.length === 0 && !staleSinceLast) return null;

  const overdueBU = overdue[0]?.businessUnit;
  return (
    <div className="space-y-1 rounded-md border border-rose-200 bg-rose-50 p-3 text-xs dark:border-rose-800/60 dark:bg-rose-950/30">
      <div className="flex items-center justify-between gap-2">
        <p className="flex items-center gap-1.5 font-semibold text-rose-900 dark:text-rose-100">
          <AlertTriangle size={13} />
          Sitrep cadence is slipping
        </p>
        <SitrepDrawer
          exerciseId={exerciseId}
          incidentId={incidentId}
          dDayHHMM={dDayHHMM}
          defaultBusinessUnit={overdueBU}
        />
      </div>
      {overdue.length > 0 && (
        <ul className="space-y-0.5 pl-5 text-rose-800 dark:text-rose-200">
          {overdue.map((s) => (
            <li key={s.id} className="flex items-baseline gap-1.5">
              <span className="font-semibold">{s.businessUnit}</span>
              <span className="text-rose-700/80 dark:text-rose-300/80">
                — promised an update at D-Day {s.nextUpdateDDayTime},{" "}
                <span className="font-medium">{s.dueAgo} min overdue</span>
              </span>
            </li>
          ))}
        </ul>
      )}
      {staleSinceLast && overdue.length === 0 && (
        <p className="flex items-center gap-1.5 pl-5 text-rose-800 dark:text-rose-200">
          <Clock size={11} />
          Last sitrep was {minutesSinceLastSitrep} min ago. IMT cadence is every 30-60 min
          for an active incident.
        </p>
      )}
    </div>
  );
}

function ddayToMinutes(hhmm: string): number | null {
  const m = hhmm.match(/^(\d{1,2}):(\d{2})$/);
  if (!m) return null;
  const h = Number(m[1]);
  const min = Number(m[2]);
  if (Number.isNaN(h) || Number.isNaN(min)) return null;
  return h * 60 + min;
}
